#!/usr/bin/env python3

citlist = ["''Ça m'gratte les couilles''",
"''C'est trash-tier ça''",
"''Bungie please !''",
"''No don't do it ! Ah ahhh !! I'm a virgin !''",
"''Pas de problème regarde !''",
"Le Warthog savonnette de Halo CE",
"''No problemo Tonton Chuck !''",
"La folie de Rathalos après avoir entamé ce travail d'archivage du Saint Lore",
"Le génie de Franckix après avoir eu l'idée de l'archivage du Saint Lore, ainsi que son génie civil pour le rendre accessible à tous sur ce modeste serveur Discord",
"''Balek, ça pue sa mère !''",
"''Skola-Mayas''",
"L'impulsion Formule 1 de D1",
"La légendaire BBT",
"''Ok, j'vais essayer de suivre tes conseils !''",
"''J'suis Légataiiiiire, et ça c'est tellement cool tellement cool, va falloir attendre Halo 4 pour savoir quoi faiiire…''",
"''Halo Info, Halo Info (Halo Info), Bang Bang TV…''",
"''Des nuiiits blanches à faaarmer les citations !''",
"''Merci Bungie d'avoir laissé la sériiiiie, car sur Reach ça commençait à sentir le roussiii…les maps tirées du solo, franchement c'est pas vraiment nouveauuu (343, 343, 343, 343) 343 Industries !''",
"Les 2 élites en coop sur Halo 3",
"Le mind game pour savoir qui passe les cinématiques en coop",
"''Tatatekoï''",
"''THAT'S A LOT OF DAMAGE !''",
"''Emotionaaal DAmage''",
"''Antisaucisse, tu perds ton pénis !''",
"''J'ai reçu une lettre, il y a un mois peut-être, arrivée par erreur, NIQUE le facteur !''",
"''Et ça ce soir, ça va s'savoir !''",
"''Fuuuuusion''",
"''Stop it, get some help''",
"''Every 60 seconds, a minute passes in Africa''",
"Toto - Africa",
"''Link in parka in Linkin Park in park''",
"La clé de Borkul la Bête",
"La givrépeire de la Confrérie Noire",
"''BTS''",
"''Quelle indignité''",
"''Où est le seigneur Aragorn ? Où est-il ?? Il est tombé'' (avec l'accent)",
"''Tomber dans le videuh videuh tomber dans le vide''",
"Indila - Dernière Danse",
"''Legless LEGO Legolas''",
"''I TRIED SO HAAARD AND GOT SO FAAAR, IN THE ENDDD IT DOESN'T REALLY MATTEEER !!''",
"''I'VE BECOME SO NUMB I CAN'T FEEL YOU THEEERE, BECOME SO TIRED SO MUCH MORE AWAAARE !!''",
"La musique de merde de Hunter parce qu'il voulait pas s'acheter d'écouteurs",
"''Valenciennes, 11h du matin…musique de merde''",
"''FAIS-MOI À MANGER J'AI FAIM LÔÔÔ''",
"''PIYAS ! SAYAS !'' (avec la mélodie qui va avec)",
"''Regret Regret Regret''",
"''Ils ne seront pas oubliés''",
"''Il me faut une arme''",
"Le Keys noir de la série Halo, comme dans les jeux",
"''Le méchaaant, le méchaaant…ouiii c'est luiii, c'est le méchaaant !''",
"''Hinhinhin je suis méchant''",
"''BaCkStReEt BoYs''",
"La Cruche Percée",
"Ce gros baiseur de Lancer",
"Les waifus trop bonnes de 10…de 10'000 ans pardon",
"La clé Squelette",
"''Caca culotte''",
"Les Égoûts de Haltevoie",
"Le mec qui se fait décapiter à Solitude",
"''JE VOUS ORDONNE DE ME DONNER CETTE IA''",
"Ce gros BG de Rolland dans Halo 4",
"Le légendaire spectre rouge",
"''De la haut je vois ma maisooon !!''",
"La sublime coque de Sagira",
"''Wow''",
"''Go go Ninjago !''",
"''Il n'y avait qu'un seul vaisseau''",
"Lokir de Rorikbourg",
"''Allez Spartans, c'est la Warzone Baptême du Feu Zone de Combat Mythique''",
"''CÉSAR ! NOOONNN !!''",
"''Moi pas aimer ici, moi pas aimer me lever le matin !''",
"''Qu'est-ce qui est vert et qui pousse au fond du jardin ? Le Démon en train de chier !''",
"''Ingrid, est-ce que tu baises''",
"''Lorsque tu comprendraaas, l'amouuur qui est en moi…''",
"''Ouuuuuh allez viens je t'emmène, on va faire un touuur sur l'autoroute ! (Oui ouais !)''",
"''Magnums, sécurité à l'épaule, le protocole''",
"Le Protocole Cole",
"Master Chief qui se promène avec sa copine dans un parc en fleurs de Reach City, exactement comme dans les jeux",
"''C'est vraiment le meilleur truc que j'ai vu de touuute la journée…''",
"''J'm'en bats les couyes !'' (avec la voix insupportable qui va avec)",
"''Chais pas j'm'eeen bats les couilles''",
"''Goutte de sueur''",
"''Maow, des crêpes, tu vas la baiser la Lucile ?''",
"''Waaah regarde Roméo, le feu ! Je vais tuer Lucile et brûler son corps !''",
"''Je suis Denis Grognard, et je viens de me péter le bide dans ma tente !''",
"Le magnifique Llwellyn le Rossignol",
"''Je chasse et je pêche par ici depuis des années''",
"''Camarade de beuverie ! Allons boire de l'hydromel !''",
"''Eh Ragnaaar, un peu d'saumon peut-être ?''",
"Le Ragnard pervers",
"''J'ai mal au bide''",
"''DE MUSIQUE !''",
"''Bah j'veux bien mais bon c'est groupe de quoi, moi j'veux bien mais bon c'est un groupe de quoi…''",
"''Baaah ok j'veux bien''",
"''Je pense tellement à toi que mon coeur ne bat plus…je t'aAaAaime tellement fort ! Quand j't'ai vue la première foiiis, j'étais dev'nu fouuu de toiii, j'aurais fait n'importe quoiii, pour un baiser de toiii, j'suis timide et réservééé, je pouvais pas t'approcheeer, il fallait le mériteeeheheheeer…*gros cri d'actrice de cul*''",
"''BITCONEEEEEEEEEEEEEE WASSA WASSA WASSA WASSA WASSSSAAAAAAAAAAA-''",
"''Soirémentééé baise sa mère !''",
"''Éléphant, banane, nique sa mère''",
"''Jawassionnn Madeleine''",
"''Hmm la bonne corde qu'on peut pas attraper hein''",
"''Connerie de jeu !''",
"''Tiens t'as vu c'est un crabe, tiens, voilà l'épée légendaire''",
"''Des déras sortaient du cratère jusqu'à c'que j'bouche le trouuu…j'ai mis un crâne comme verrou et pas une seule des déras n'a réussi à comprendre…''",
"Les Drôles de Petites Bêtes",
"''Par le sang du Christ elle est poursuivie par un ours !''",
"''J'ai vu une grosse bête''",
"''Regardez là-haut, un terroriste ! C'est un tueurrr, il veut me tuer''",
"''Ce gros balourd de Hagrid''",
"''Siiiiiiiis''",
"''Vous aurez jamais mon traîneau !''",
"''J'aime mettre mon pénisss dans des yaourts (dans des yaouuuhourts), banane pêche ou bien nature, même avec de la garnituuuhure !!''",
"''C'est un temps idéal pour une petite pipe !''",
"''Ça me rappelle quand je faisais les putes à Maubeuge''",
"''Il va se beuj' dessus''",
"''J'ai redoublé ma seconde…''",
"''Oh merde, j'ai oublié de poster ma lettre à Sophie''",
"''Amuse-toi bien, Gadget !! Hahahaha…hahaha…haha…''",
"''I'm stuck step bro…''",
"Le titan skating de D1",
"Le titan flying de D2",
"Le hunter flying de D2",
"Le warlock + sword skating de D2",
"Le passereau Spiderman",
"Le passereau Jamaïque",
"Le Zen Meteor de Rathalos",
"Les moteurs pour passereaux de Xûr",
"''Il est où Xûr ?''",
"''...sees…''",
"Tritosor",
"Le cri de Keunotor",
"Le cri de Chamallot",
"''Un titin, un chasseuw et un arcaniste'' (faut pas oublier l'accent)",
"Ronflex",
"''N'oubliez pas ce que dit Aragorn : il y a toujours de l'espoir !''",
"''Pour SEGA !''",
"''Pendant ce temps-là, à la tour Karine…''",
"''Tatakilu''",
"''Piiipalapa poop''",
"Les arbres en Y de Assassin's Creed 3",
"''Et alors là le mec il m'dit quoi, quoi tu veux m'baiser moi ? Donc là j'lui dis ok bah on va faire un constat……et alors là je lui en mets une comme ça, une autre comme ça…''",
"''Ah mec dans ce jeu franchement t'es blindé, tu peux taper comme ça, comme ça aussi''",
"Le club de motards de Franckix sur GTA",
"Les vols de la mort qui tue en moto sur GTA",
"Les rencontres en BMX sur GTA",
"Le skin orange du Canon Tracteur sur D2",
"Le revêtement du Jugement des Neuf sur D2",
"Le Coup de Minuit sur D2",
"Le légendaire Manannan SR4 sur D2",
"Les murs invisibles insupportables made in Bungie",
"Les hors-map de fou sur Halo et Destiny",
"Le hors-map tout en bas du Récif pour chill avec les vrais, mais que contre le mur",
"La map Haven",
"La map Rivages du Temps",
"La map Hemorrhage",
"Le serviteur qui pouvait pousser les randoms au Récif sur D1",
"La Force Arcane : la Lune chez Variks sur D2",
"''Sur ce coup-ci ma tête est sur le billot pour vous équipe Noble !''",
"''Un Dévot ? On est sur un gros coup commandant !''",
"''Ouais 'fin voilà, y en a qu'aiment pas vraiment laisser un boulot en plan…''",
"L'easter egg de la boîte de nuit sur Halo Reach",
"La Monkey Family",
"''Scout Decoy''",
"''Un gros GG à lui !''",
"''Le sol était glissant mdr''",
"''MacDoLaGale''",
"''Eh Fred ! Hadoooken !!''",
"''Chez Twix droite, on coule le Carapuce, chez Twix gauche on coule''",
"''Eh dis donc il ne reste plus une seule pute''",
"''Tu ne crois quand même pas que je les ai toutes sodomiséeees oh non…''",
"Olivette",
"Huile d'olive",
"''Touf, moray gadjo, lalalalalala…'' (avec la mélodie qui va avec)",
"La chance de lutin",
"''Méfiez-vous des enfoirés louches de la toile !''",
"''Votre mot de passe ne vous donnera pas la Recon''",
"Les sessions succès sur Halo 3 et Reach avec les 45 invités",
"''Ahh ça m'gratte !''",
"''Faut Ferrari ça va plus vite''",
"''Le rire, c'est la raison que l'on écoute''",
"''Eh toi là-bas, pourquoi t'es aussi moche ?!''",
"''C'est toi qu'a mangé tous les Pitch ??''",
"''Ooouuuvre j'vais t'bouffer !''",
"''Les ogres c'est comme les couilles !''",
"''J'peux res j'peuch j'peux rester avec toi ??''",
"''J'partais pouuur schaps...et puis p'tit à p'tit le drone il s'avance...sance...''",
"''Ça y est ils l'ont fait : ils ont mis la rue à sens unique, et impossible pour nous de nous garer''",
"''Testatostestatostestestestastostestestas...''",
"''Autistotestastostestestastos...''",
"''Eh j'suis le seul connard à faire voler un drone à la baraque ''",
"''My big burger sauce barbecue...my chicken corner...cette sauce qui t'accompagne...''",
"''J'suis pas gros j'suis montagneux''",
"''Ton chat-bite tu peux te l'foutre au cul, et l'Étoile Noire avec !''",
"''Un tyrannosaure ? T'es sûr que t'es pas un énorme tiramisu ??''",
"''Moi j'ai carrément peur qu'il bouffe la maison''",
"''Son mot de passe c'est Francky Vincent''",
"''Messieurs, ils sont grands, ils sont rapides, vous niquer c'est leur idée du tourisme !''",
"''Votre Malabar est un chasseur, il a amené ses chiens''",
"''Le Prédateur Ultime…''",
"''Au fait j'pensais, j'crois qu'on va crever !''",
"''Ceci est mon...mon urine, je la bois de manière vivante''",
"''Faut que je me fasse un chocolat au lait''",
"''Stormy Pingouinz''",
"''Ouais bebeeeyzzz !!''",
"Le légendaire combat de hottes entre Lio et Bézéké pendant que le reste du groupe devenait sourd",
"''C'est l'eau de vie''",
"''Avec la Vega Missyl vous êtes satellisé''",
"''C'est quelque chose à ne pas mettre entre toutes les mains''",
"''À 150 km/h, on n'est qu'à la moitié de l'accélération : ça ne laisse pas indifférent''",
"''Regarde !!''",
"''Euh…c'est chiant''",
"''Pays d'la vache !''",
"''2 fois ,5''",
"La map PvP Abruti ! de Minecraft",
"''Ah bon il a pas de prénom !?''",
"''Il a la voix fatiguée...''",
"''Pignon !! J'arriiive ! Pignon !! J'arriiive !''",
"La mythique croix gammée de Bézéké sur Minecraft",
"''Les mecs, regardez en haut !!''",
"Le légendaire thème des Avengers",
"''Tu sais c'est Franck Sombre…50 Nuances de Sombre, 50 Nuances plus Sombres''",
"''Mais non j'déconne !''",
"''Mais nooon j'rigole''",
"''On fait tous caca une fois par jour''",
"''Ici Jamy, planète Terre : dans ton cul''",
"''Merde y a un T4 en face''",
"''G for Greedy''",
"R for Rathalos",
"D for Doctor",
"P for Pray",
"L'autisme chronique de Rathalos",
"''Euh on a pas la même Mort Rouge !''",
"''La Bombe Novaaa j'la meeets juste sur tua''",
"''Tales of Anusia''",
"''Et bien salut à tous, c'est Michkapi''",
"''Aussi mortel que le cancer AYAA''",
"''T'aimes euh…les blondes ?''",
"''Ah ouiii…ah oui oui oui''",
"''Maman ! Qu'est-ce que tu fais sur Azar ?!''",
"''The other day, somebody told me to go fuck myself…and you know what ? I can !''",
"''I wish my dick was that big''",
"''There's no reason to complain''",
"Nightcore - Là-bas",
"L'araignée de Lio",
"La tique de Blacky",
"Les insectes de Dark Souls",
"L'araignée géante chez Rathalos pour pas qu'il joue à Dark Souls",
"Les soirées moisies de Rathalos",
"Le chat coupé de Blacky",
"Le rire du père à Blacky",
"''2 chiennes lol''",
"''On fait un Athéon pour le lulz ?''",
"''Lui j'vais le claquer comme les clowns''",
"Les abdos à Bézéké *q*",
"Les poignets à Bézéké *q*",
"''Faut tout que j'gâche tout !''",
"''Allez hop ta gueule !''",
"Le tristement célèbre Doliprane tueur de chiens du frère à Franckix",
"''Oh ça pue ici, c'est dégueulasse Franck !''",
"''Mamaaan mes Chocapics !!''",
"''TA GUEULE MÔMAN !!''",
"''Ah j'ai pété ça pue''",
"Le fauteuil de Lio qui fait un bruit de pet quand Lio l'avance du coup on dirait qu'il pète mais en fait non",
"Les pets de Lio à 2cm du micro parce que celui-ci est posé à 2cm de son anus",
"''EH EH ARRÊTE LÀ''",
"''Alors les minables ? On a une crise d'urticaire ??''",
"''Vous avez l'air pâle...ce serait pas l'ataraxie ?''",
"''Hmm...hmmmm...hmmmmmm...la sauce est très bonne''",
"''Dès midi, c'est la grande affluence...on prépare des bassines pleines de saaaucisses''",
"''Jeuj renoi jaaj''",
"''Tu es tout bétonné''",
"Le niveau 200 sur Dark Souls",
"''Eh j'vais l'niquer !''",
"''Oklm en fond de map avec Rathalos''",
"La campe noble de JB",
"Le black avec son sac banane",
"Les trickshots nobles de JB",
"Les manettes de Wii de la mère à JB",
"Le smegma à gratter",
"La grosse voisine la grosse à Rathalos",
"La perceuse du voisin à Rathalos",
"La musique de gros baiseur de Rathalos",
"Le casier judiciaire de Bézéké",
"Le casier judiciaire de Obi",
"La caravane de Obi",
"La Xbox dans le jardin de Obi",
"La guimbarde de Obi",
"La bolo de Obi",
"''OUAIS J'ARRIVE !''",
"Arte - L'Inde Sauvage",
"La position gainage",
"Rathalos qui joue debout",
"''Minecraft c'est le jeu pour les pédés''",
"''LEGO City gnneee''",
"La musique de l'écran titre de la beta de Destiny",
"''J't'ai connu des jours meilleurs Lio''",
"Le traïleur de la beta de Halo 5 Gwardianz",
"Halo Gabi la légende",
"Les assassinats sur Halo Wars",
"Le clan Destiny Guardians",
"Le Clan des Ewoks",
"''Taniks n'a pas de clan…Rathalos n'a pas de clan…''",
"''J'lui ai mis un gros nope''",
"Le quickscope whip",
"Les commentaires haineux de Franckix sous couverture sous le clip Single Halo Clips de Rathalos",
"Le ninjatage de FCP Blacky par Idriss Auxo",
"Le ninjatage de FPC Nargacuga par BlatteVico",
"Les noms de clips improbables dans les partages de fichiers",
"''FPC Narga cul ga''",
"Halo Adolf Hitler",
"Les commentaires haineux de JB sous la vidéo Destiny de Cyprien Gaming",
"''Cyprieeeeennn Squeezie Gaming''",
"''Ouais faudrait que j'le fasse ça...''",
"L'haleine de Sardoche",
"La config Talkie Walkie sur Halo 3",
"La map QG de la X Wave",
"''Petite partie perso à 2 ;)''",
"''Nice bubble in Mayhem''",
"''Belle action ;D''",
"''Ouep x)''",
"La balise de Bézéké sur Orange TV",
"Castle Miner Z",
"Avatar Warfare",
"Motocross Madness 2",
"Le Régicide avec JB",
"Les raids Athéon avec Hunter",
"''C'est Trop Long à Expliquer''",
"Sparrow Pioneers, Sparrow Legends, Caelesti…",
"''Dwemers''",
"Dwemers",
"D i n o s a u r e",
"Les rêves de Rathalos",
"Le jeu ''Dinosaure'' du rêve de Rathalos",
"L'expérience sociale de Rathalos pour revivre La Guerre des Mondes en rêve",
"Le carnet avec les bouts de rêves de Blacky",
"''Lourd des jambes pour prendre le bus''",
"Le fauteuil de Blacky qui sent le poisson (le fauteuil pas Blacky)",
"''NBA 2k 2016''",
"La boîte de NBA pour tenir le velux de Blacky",
"Blacky sur La Panse",
"Blacky en Bannière de Fer",
"La manette défenestrée de Blacky",
"''La Bannière de Fesse''",
"''OSIRIS LÀÀÀ''",
"Rathalos qui devient zinzin sur Dark Souls 3",
"''Ah salut || ||| | ||'' (Amnésia)",
"''Rite de l'Orage'' (avec la voix qui va avec)",
"L'emblème de Noobi qu'on a jamais su comment l'avoir",
"Le mythique emblème ''Oryx part en vacances''",
"Les terrifiants croissants de AutomneRime",
"Le jeu de Bézéké avec les dinosaures là",
"Le ping de 999 de Rathalos sur Rocket League",
"''Pokémon Pikachu''",
"Le Hoothoot Shiny du frère à Blacky",
"Airmure dans Donjon Mystère",
"Zigzaton",
"Férosinge",
"Totally Reliable Delivery Service",
"Ed Sheeran - Shape of You (Nightcore French Cover)",
"La musique Halo 3 Armor",
"La Prison de Jokerman",
"''C'est Jean-Marie Bigard ma couillasse ! Tu veux m'sucer ou tu veux que j't'encule ?!''",
"''Et là le gars il arrive il défouraille, LA LA LA LAAA''",
"''Select, Use, sélectionnez un personnage, sélectionnez l'item à ramasser, retour au menu, retour au jeu...mais c'est pas fini ! Parce que le mec maintenant qu'il a l'item il faut lui dire de s'en SERVIR ! Ça pourrait être comme tous les jeux du monde où tu peux tirer à l'infini, mais là NON !!''",
"Le légendaire BR Arctic",
"Le BR Dune",
"''C'est génial, je prends mes affaires !''",
"''Squallalah, nous sommes partis !''",
"''Rien du tout, poisson, rien du tout''",
"''Génial, j'ai hâte de tout recommencer !''",
"''Heyyy ça vous a plu ? Alors on continue !!''",
"Bézéké qui tourne dans des caves à Paris parce qu'il met du Justin Bieber à fond dans le groupe de Jokerman avec l'aide de son agent infiltré qui peut l'inviter dans le groupe sur invit même si il se fait virer",
"L'amour fou de JB pour JohnDexology",
"''Ah ouais les Power Rangers toute notre enfance''",
"''Le plus grand des détectiiives…oui c'est luiii, Sherlock Holmes le voiciii''",
"TitanPlanet",
"MLS Didacte avec un E",
"''Ah ouais Boruto à l'ancienne''",
"''Merdz''",
"''Blacky le dormeur x)''",
"''Cropta le Coiffeur XD''",
"Bengous - Tié la Famille !",
"''Saints Row c'est le GTA du pauvre''",
"''Damn you're weak !''",
"Blacky et sa famille nombreuse sur Skyrim",
"La voiture de la famille Bamboula sur GTA",
"La neige en intérieur sur la partie Skyrim de Blacky",
"Les succès Skyrim de Rathalos",
"Les succès 360 perdus de Rathalos",
"Le légendaire avatar bleu de Franckix, résultant sur son ban jusqu'en 9999",
"Lio ce sale Elfe Noir",
"L'élastique pour monter le pilotage sur GTA",
"Le succès Chercheur d'Or de JB sur Skyrim",
"Les succès Gears 2 de JB",
"''J'ai fait tous les Gears''",
"JB et sa console en vacances en Espagne",
"''Cringe Boy''",
"L'Époque Révolue",
"''On aperçoit au-dessus de mon épaule un orbe de lumière''",
"L'époque des 9 orbes de Lumière",
"''Hop, petit coup de boisson''",
"''C'est bon je vais manger du pain''",
"Les repas speedrun de Blacky à 18h",
"Les repas interminables de Lio à 22h",
"La mythique co de Lio",
"La co de Bézéké quand il était dans la cabane du jardin",
"Les écouteurs de la soeur à Bézéké",
"L'accent du sud de la mère à JB",
"La voix de Shrek de la mère à Rathalos",
"''Mon code d'erreur préféré sur Destiny : Baboon''",
"''Oh bah ça c'est rigolio''",
"''Dans Monster Hunter, y a toujours cette peur, d'affronter un monstre nouveau sans qu'il t'fasse la peau…des Rathalos et des Rathian j'en ai tués par milliers…et le Zinogre, ce gros loup électrique…et Alatreon ça rime peut-être avec con, mais rigole pas trop car en 2 coups il t'bat !'' (version censurée)",
"''Lionette, Blackette, Franckette, Blanquette…Jessie Shepard''",
"Le succès des 5km de saut en quad sur Defiance",
"Le succès des 1000m de nage sur Defiance",
"Bézéké, militant Sea Sheperd",
"Bézéké le vegan chez McDo",
"''Lio l'ancre''",
"La mythique escalade en galion sur Sea of Thieves",
"Le putain de confinement sur Sea of Thieves",
"Les délicieuses recettes de Maïté sur Sea of Thieves",
"Le big big BIG big Shack sur Anthem",
"La super monture de Franckix sur TESO",
"Les Éboulis de TESO",
"Le légendaire Sea of Thieves",
"''Qui pour Asile ?''",
"La Quête Exotique",
"''Destiny 2 Renégats disponible le 4 septembre, précommandez dès maintenant et obtenez la cache exotique de Cayde''",
"Le DPS de Biscuit au Rapace Noir alors que Rathalos s'est cassé le cul à le carry dans la mission du Fuseau Noir la veille",
"Le vaisseau Chanteur de Vienne",
"Le vaisseau Chance Incroyable",
"Les armes rouges avant Athéon",
"''Sympa ton vaisseau, on se demande grâce à qui tu l'as eu''",
"Le bus magique",
"Le club Sparrow Flying School",
"Le club Mangaka FR",
"Le club Destiny Destiny Destiny",
"Les billets de NeoMathael",
"Les 5 points de grimoire en plus de Rathalos",
"La carte de grimoire d'Athéon",
"La technique des alpinistes avant Oryx",
"Le légendaire Tortue Furious",
"Le légendaire RvE Nico",
"Le légendaire Un Bougnoule",
"''Nan mais les gars vous marchez sur les grenades'' (avec la voix qui va avec)",
"''Va faire le lol ailleurs''",
"''Calus…suce''",
"''Yoba yoba yoba''",
"L'avocat qui avait un gros porn en fond pendant un raid Aksis",
"''C'est avec tristesse que j'apprends qu'Eiyuu Unmei, le grand héros légendaire, nous a quittés…''",
"''Rest in RIP''",
"Le pet railgun pénétration 1000 de Franckix sur ses draps",
"''Le ragloune''",
"Ce gros baiseur de NxG Ghost",
"Ce tombeur de DGA Nakrule, avec son pompe cheaté de salope là",
"CourageLapin",
"Le sublime Ronan Reach",
"Le clip Halo QG de Rathalos sur Halo 5 alors qu'il avait juste envoyé un clip Halo 4 genre 2 ans avant",
"''Je pourrais lui offrir une Warthogz, il est pilote pro''",
"Le T2 Wyvern",
"Les bites des zombies sur Outlast",
"''Ici Shaw Han, je suis un âne''",
"''Du calme ! Je sais la pression que vous avez !! Oubliez-la !!!''",
"''La pression je la bois moi''",
"''La boule magique !''",
"''La ferme sale tâche de caca",
"''Je te tire dessus !''",
"''Je faisais de la patrouille et d'un coup le ciel s'assombrit parce qu'un event commence, et là devine quoi...je m'approche de l'event et là PAF ! Le Warsat il me tombe dessus !!''",
"''Un matin y a un ingénieur du son qui est allé au travail avec sa fille, et quand ils enregistraient le cri d'Omnigul la petite a crié, du coup ils ont gardé son cri à elle''",
"''Ha ha haaa...attends mais c'est pas drôle''",
"La mythique redécouverte des YouTube Poops en jouant à Skyrim, transformant à jamais notre langage",
"''Est-ce que vous trouvez que c'est pas complètement con quand vous demandez à un enfant votre chocolat vient d'où il vous répond eeurk...c'est con moi quand j'entends ça j'vous jure j'ai envie de chier là''",
"Le mythique Jean-Pierre Coffe",
"L'amour fou de Bézéké pour la YouTube Poop Star Wars",
"''J'ai très envie de pisser, où sont les toilettes''",
"''JE SAIS PAS''",
"''Je sais que tu le ferais, je sens la violence…de ta bite''",
"MLG Mace Windu",
"MLG Mario",
"''Oh putain d'sa mère, Diablox12 !!''",
"''Mommy get the camera !!''",
"''La jeune Mary Jane Watson est une prostituée…c'est cool ça !''",
"Rathalos se prend une dérouillée de l'espace",
"''Vous avez une tête de cul…tout est dit''",
"''Petit goût de fesse''",
"''Dream Team en papier P''",
"''He is speaking the language of the Gods''",
"Fate Hollow Ataraxia",
"''Je suis Archer''",
"''Le quickscopeur, le campeur, le hackeur''",
"''Dickscoped''",
"''Ayy lmao''",
"''Hey look, a FaZe Application''",
"''RIP Altaïr Balaweed''(avec la musique qui va avec)",
"''CRAWLIIING INNN THE DEEEEEEP''",
"John Xina",
"''Zushie zushie bing chilling, ao shiwa...'' (Chinois LV15)",
"''Oh putain, j'ai aucune idée de c'que j'fous là !''",
"''For the first day of Christmas the turtles gave to me, a pizza with pepperoni''",
"Dehao Zang - Ching Chong Hon Chi, avec en feat la meuf trop naze là",
"''Did I scared you ?''",
"Obi qui nique les 200k en Baptême du Feu sur ODST",
"Le thème de Halo 2 à fond dans le micro pour détruire les oreilles de tout le groupe",
"Les images de joueur Terminator Genysis",
"Les images de joueur de joueurs de foot",
"Le dinosaure Transformers pour avatar",
"Lio et son Halo Reach en espagnol",
"Le script de Franckix pour devenir Légataire sur Halo Reach",
"Le ratio de 0,01 de Franckix sur Halo Reach",
"Le winrate de 100% de Rathalos sur World of Tanks",
"Rathalos dans le top 3 mondial de Fate Grand Order et le top 3 Corée de Higurashi",
"Le deck Zombie Team de Rathalos",
"Rathalos le joueur pro World of Tanks, World of Warships et War Thunder",
"JB le joueur pro Pokémon et Yu-Gi-Oh!",
"''Lio road to SSL''",
"Warface",
"Defiance",
"Anthem",
"Les fonds de poubelles du Gamepass",
"''ROCK AND STONE !''",
"''If you don't Rock and Stone, you ain't coming hooome !!''",
"Bézéké qui retourne la démo de Destiny",
"The Beta Was Better",
"Le Fan Club de Jokerman54",
"''Ahlala y avait vraiment tout le monde à la beta de Destiny...''",
"Les démos foireuses de Division, Anthem et Outriders",
"Lio et ses skins Gotham City Impostors",
"Dragon Age Inquisition",
"Dragonball Xenoverse",
"''Leo that is you ?''",
"''Naruto Shippûden : Ultimate Ninja Storm 3 !''",
"Le succès du kill de super loin au Tomahawk sur Red Dead Redemption",
"Beeg.com",
"Le fameux serveur Minecraft",
"Les grosses images de hentai bien crades sur Skype",
"Le deuxième serveur Minecraft mais avec Lio en host",
"Le circuit Minecraft",
"Le Pictionary sur Minecraft",
"L'image de joueur de tueur à gages sur 360",
"Le Freezer pas cadré de Noobi",
"La Ménagerie lugubre",
"La voix de Noobi",
"Le viol de Noobi sur son propre live Halo Reach",
"Le Nargacuga pixelisé de Nargacuga",
"Les 28492057 images de joueur de Blacky",
"La map Octagon avec l'arbre sur Halo Reach",
"''Mirage...is about to blow !''",
"''Dust...is about to blow !''",
"Harm's Way",
"L'image de joueur de Bionic 973",
"L'image de joueur cursed de Lio",
"Le requin de Bézéké",
"''Le Pas de Couilles du 33''",
"''Toi tu prends tes cliques et *fiout*''",
"Purple X Wave",
"Poseidon X Wave",
"Phoenix X Wave",
"Les 3839104 serviteurs du premier Solstice",
"La mission en tank du premier Solstice",
"''Amanda…HOLLIDAAAYYY''",
"''Johnny…HALLYDAAAYYY''",
"''Dans la GÉNÈÈÈSE''",
"Michel Forever - Forever Tonight",
"''J'n'oublierai jamais cet été qu'on a passey, J'TEEE LEEE JURE, never forget, j'n'oublierai jamais ce mois d'juillet J'TEEE LEEE JURE, never forget !''",
"''Ce refrain qui te PLAAAAÎÎÎT''",
"''Jevaismourir.com''",
"La myopie aiguë de Rathalos sur Sea of Thieves",
"FPC Aveugle",
"FPC Autiste",
"FPC Artiiiiiiist",
"FPC Tunning",
"FPC Ferocity",
"L'addiction gravissime de Yoshi aux jeux-vidéo",
"''J'vais rentrer chez moi j'vais m'faire un goûter''",
"Le restaurant Hypothalamus",
"L'ours menaçant de Gare du Nord",
"La bière goût poussière de Gare du Nord",
"La route mortelle de Bussière-Galant",
"La Fare-les-Oliviers",
"Le profil de Blacky en Belgique",
"Oxygène qui confond Rathalos et JB, et du coup il parle mal à Rathalos",
"Le célèbre mode Assasin de Halo 4",
"''BR Magnum...''",
"'Ceux qui jouent moins de sensi 10 je sais pas comment ils font'",
"La map Escape from Mars et les comptes secondaires de Franckix qui tenaient le serveur 24/7",
"Les mythiques jumps à la Tour",
"L'emblème du SIDA",
"Le mythique Gabriel Night, célèbre romancier américain",
"''Ce que vous me dites là c'est du chinois''",
"''Ok donc là j'ai glaçon + cheval je vais les niquer''",
"''Shi-Hen + Fuma + Dojo...''",
"''Oui, je confirme...j'étais allé voir le commissaire Le...Lébert lui poser des questions, par exemple, pourquoi les poils retrouvés sur les lieux du crime sont roux, alors que, ceux des loups du zoo...sont gris !?''",
"''De la porcelaine...très cossuuuu...cette forêt est très grande''",
"Le malaise des gens qui sont encore sur la première Xbox",
"Le RROD de la 360 de Blacky",
"La Series W de JB",
"L'adresse mail Wanadoo de Rathalos",
"LaPoste.net",
"Yahoo.com",
"Les rêves de Xbox de Lio",
"Les rêves humides de Franckix",
"La X box One X box One X box",
"L'emblème magique de Franckix",
"L'ancienne technique à base de suicides collectifs pour farmer la Boucle Imaginale",
"''La Boucle Imaginale, ani salidade, ninininin suicidas''",
"Les 10'000 km de Franckix sur Skater XL",
"La mythique Boucle Imaginale Hors-la-Loi / Luciole",
"Hors-la-Loi / Boucherie, ce combo god-tier",
"La radio mexicaine de GTA",
"Ceixo",
"Don Omar - Virtual Diva",
"JB et son Souffle du Dragon sur Cropta",
"''Ça c'est le Dragon's Breath…l'odeur du bacon et du carnage…''",
"Les potes Discord de JB",
"L'ailier de Rathalos",
"Les 1v1 alcoolisés à 3h du matin",
"Le fusil auto de fils de pute de Rathalos",
"''Ok les gars je suis à 5min31 allez go !''",
"La musique insupportable du Guide quand on pouvait pas passer les cinématiques (nin nin niiiiiin)",
"La célèbre MàJ de l'image des mousses métallifères",
"''Vous n'avez pas été recomposé…en théorie, cela est impossible !'' (avec la musique et en boucle pour plus d'immersion)",
"''Niiin niiiiiiiin…nin nin nin nin niiin nin niiiiiin…nin nin niiiin niiiiiiiiin…nin nin nin nin niiin nin niiiiiin…je sais je chante bien, c'est très bien''",
"''Excuse-nous de pas lire le lore''",
"''Ils ont moddé eux ils méritent pas la Fotus''",
"''Ils l'ont forcément moddée leur Deadeye''",
"Les atouts moisis de Halo 4, genre celui des tourelles là",
"Les dialogues cringos du Spartan Ops de Halo 4",
"''Carte mémware''",
"''As the Rock was saying, finish your saaauce !''",
"''RAAAH…casse les beulz sale connard là !!''",
"''Camouflage activé''",
"''Comment ça va Dragfire…''",
"''Bonjouretbienvenueàtoussurcenouvelépisodedulet'splaysur HALO 3 ODSTaaaay !!''",
"''Ça c'est mon Blacky MLG Ninja à moi ça <3''",
"''Rathalos viens en 1v1 je vais t'instruire''",
"Le légendaire HF4 Racer",
"''Liiv <3''",
"''Comment ça va ma biche <3''",
"Les 1v1 de 2h sur Halo 5",
"L'ange gardien qui distribuait des BRs Longshot en Warzone sur Halo 5",
"Le paquetage ultra safe",
"''J'suis en train de m'faire enculer par un Rampant''",
"''Le Wasp Freestyle''",
"Ce malaise pesant de Wass Freestyle",
"''Ah ça y est on est dans l'espace là, on approche de la Lune''",
"''Veto guys veto guys veto veto guys veto…''",
"''WAKE UP GUYS''",
"Rathalos qui passe Onyx avant Electro et Fero en Élimination sur Halo 5",
"Le montage de Rathalos",
"Le légendaire Dark Orbital",
"Le légendaire 1v1 SMG Roquette",
"''J'ai pété sur le chien''",
"''Les gars faut qu'on com plus vous commez pas as- *énorme rot*''",
"''Nice…ass''",
"Le légendaire double pet axial de Franckix",
"Le caca challenge",
"''Les gars c'est quoi cette merd…INOXTAG INOXTAG''",
"''NAON C'EST DE LA MERRRDE !'' (accent du sud)",
"Les légendaires pipis avec le micro",
"''PIPI !''",
"''Deacon Pipap !''",
"''C'est okkkkkaaayyy !!''",
"''Coca bien frais chacal''",
"Les Kinder Bueno de Bézéké",
"Les Kinder Choco Fresh de Bézéké",
"Les Kinder Pingui de Rathalos",
"''Lanny, apporte-moi mes clams !''"
"''Cac cac cac cacaaa !''",
"Les promos Domino's Pizza sur Rocket League",
"''Ton cul m'a manqué Babouche''",
"Le skill aléatoire de Bézéké sur Rocket League",
"Le clan hyperactif sur Clash of Clans",
"''Une queue de billard quasiment''",
"''Et bah moi d'abord j'ai plus de chromosomes que toi !''",
"Les parties Social de 7h sur la MCC",
"Le prof de maths interdit bancaire de Franckix",
"''Ça c'est ma fusée enculé d'ta mère, armée calibrée batard !''",
"Le pote Sami",
"''C'est tout à fait, incroyable''",
"''GG les gars…'' (avec la voix de merde qui va avec)",
"''CLIGNANCOURT !''",
"Les missions Perfection de Max17",
"''93 zone rouge, ici c'est hardcore, mets toi d'accord''",
"''Elle eeest daaans ma bite, elle ne m'abandonne jamais, elle me suuuce la queue, à chaqueue voyage !'' (avec la mélodie qui va avec)",
"''Je suis sur l'autoroute de T'Savo, à l'est de Voïïï, je suis blessé, y a quelqu'un ? Répondeeez''",
"''Maydayyy, 3 Charlie 6, quelqu'un me reçoiiit''",
"''C'est qu'une simple façonnn de communiqueeer'' (avec la mélodie qui va avec)",
"''Vous pourrez fumer votre herbe dans l'herbe''",
"Le ban de 14 jours de Lio après avoir insulté un admin sur BF3",
"Pokémon Emeraude Plus",
"Le DVD Dragonball Evolution de Blacky",
"''J'te bourre le fion façon hardcore, j'touche le fond j'creuse encore, la vaseline c'est pour les pédés, moi j'y vais à sec avec du pâté !''",
"Rathalos le weeb",
"Blackykoojap",
"La Ligue des Héros Galactiques",
"''Arigato Gozaimasu Franckix San''",
"''RAZENGAN''",
"''Shirai Tensei...Shirai Tensei...Shirai Tensei...Shirai Tensei...''",
"Les kaméhaméha enchaînés de Dragonball Xenoverse",
"One Piece to Chie",
"Naruto to Boruto",
"Norauto Shippûden",
"Dragonball Super : Battle of the Gods",
"Dragonball Super : la Résurrection de F",
"''Battle of the Gods...Batlle of Zizi''",
"''Gros pipi, gros caca, gros nénés''",
"''Je suis tour excité, nichon''",
"''La maison de ta mère, la maison de ton père, la maison de ta femme, la maison de ta grand-mère !'' (avec la mélodie qui va avec)",
"''J'aime tous les sports…surtout le fouf''",
"''Ah excusez-moi, c'est un match de foot *gros bruits de hentai en fond*''",
"Les cris de hentai et la célèbre Hentai Song à fond dans les hauts parleurs de Lio avec ses parents à côté",
"''C'est pas la première fois que j'te la mets hein ?''",
"''T'es nul par ta faute''",
"''Eh m'sieur j'vous lave la vitre ?''",
"MC Circulaire - Sodomie",
"garde",
"L'odeur de la chambre à Franckix",
"L'exil de Bézéké",
"Le speedrun de Human Fall Flat",
"Le UNO qui marche jamais",
"Bézéké qui tryhard sur theHunter Call of the Wild",
"Bézéké qui joue sa vie au Monopoly",
"La migraine de Rathalos sur Terraria",
"La nausée de Rathalos sur Gears of War 3",
"''Alors il est où FaZe Wartek là''",
"Le Model 1887 sur MW3",
"''Alooors Blacky, on se prend des get rape ??''",
"L'égide du Crabe",
"''Bonjour à tous, c'est MrLEV12, au SPAS12''",
"Bref, j'ai monté le SPAS12 niveau 28",
"''Je l'ai regardé il m'a regardé''",
"''TANAKA FAIS GAFFE !!''",
"''Tanaka tu veux dire quelque chose ?''",
"''COOOLE TRAAAIN''",
"''On s'est battu pour une guerre qui n'était pas la nôtre''",
"''Ce n'est pas le moment de se demander ce qu'il y a dans le ciel''",
"''MARCUS PHÉNIX''",
"Enjoy Pénix",
"Pénaldo",
"FPC Nargacuga = Jean-Balthazar",
"''Ciao les merguez''",
"''Je suce tous les zboubs de Paname''",
"La musique qui fait ''Kesikesaaat at at at its, atat its'', celle d'un montage de Electro là",
"''Top 10 des Nombres''",
"Le remix Expecto Patronum de la mort qui tue et la danse qui va avec",
"Hypnomade",
"Algue",
"Magmar",
"Archéro",
"Mystherbe",
"Pifeuil",
"NieR Automata VS Ori and the Blind Forest",
"''Ori and the Willz of the Wilsps''",
"''Zelda : Links Solekwing''",
"Naruto the Last",
"''On rit un peu moins maintenant monsieur le comique''",
"''Condamnez le labo !''",
"Reaper qui prend le pouls de Destroyer",
"Le marchand de sable est dangereux avec son sable",
"La chanson Tout Est Super Génial du film LEGO",
"Le Roi Scorpion",
"The Rock",
"''WHO ?!''",
"''Copa...Copa CaBaNaAa''",
"''Here we go my animz, hereg EEEEHH''",
"''The damn wrestlemania, the damn people, the damn shesh, uuuuuu...uuuuuUUUUUuuuu...uuuuuUUUUUAAAAAUUUuuu...uuuuuUUUAAAAuuuuUAAAAAuuUAAAA !!''",
"''Ef if ef if somAAAAAAAAALALALALALAAAAAAA''",
"''I did it for the cock...I dit it for the pepe...I di I da daa AAAAAA''",
"''Finally...illy...the Rock has come BACK to the BACK...the Rock has come BACK to toot *gros bruit de pet mdr*''",
"''There is no fucking way into the mountain''",
"''Airborne fire bee''",
"''Harryyy...de l'eau...''",
"''Harry Potter est mooOoOom !''",
"Julien Chièze Gaming",
"''Can you imagine...meeeeemes''",
"''What happened to MEMES''",
"''Can you pay me in advance...snance''",
"JB le top 1 Assassinats en plein vol sur Halo 4",
"Franckix dans le top 100 FFA sur Halo 5",
"''Si vous avez des problèmes de bite, ne pénétrez pas un homme à l'hôpital''",
"La saucisse grillée de Motus",
"''C'est ouite lettres''",
"''J'm'en bats les couilles, J M E N, B A T S, L E S, C O U I 2L E S''",
"''Dédicace à Jamy, l'élite du rap''",
"''Ouiii saluuut c'est Keurby, j'voulais savoir si j'avais pas oublié mon Halo 3 eaudste dans ta console...''",
"Les images hantaient de Sonic",
"''On a besoin d'huîtres''",
"Fazlija - Helikopter",
"Bézéké et ses théories sur Xavier Dupont de Ligonnès",
"''Soichiro Yagami hein ?! ESPÈCE DE CONNARD !!''",
"Top 10 Anime Betrayals",
"Top 10 Anime Deaths",
"L'agence Blacky-Franckix sur Halo Reach",
"Le Revenant de Blacky",
"''Trois niveaux par semaine'' (avec la mélodie qui va avec)",
"''Deux acolytes au bout du monde, si différents'' (avec la mélodie qui va avec)",
"Le légendaire combat entre le Chien d'Or et le Taureau Ailé",
"Les super loots de Nuit Noire de D1",
"Le Guade",
"Gad Elmalaise",
"''Pierre tu veux mon anus ?''",
"''Si tu veux le savoir c'est le moindre de mes soucisses !''",
"''C'est pas très halal le salami Sacha, prends plutôt tes gnocchis à poêler s'il-te-plaît''",
"''Tu sais pas parler ?''",
"''K''",
"''Potassium''",
"Le speedrun de Franckix pour aller de 0 à 400 de Lumière en moins d'une heure",
"''American people hate french people because american people have the connexion but french people are stronger''",
"''Bien évidemment, bien évidemment, BIEN ÉVIDEMMENNNNNT''",
"''Sacha et ses amis se rendent à Carmin-sur-Mer...euh...Carmin sa mère''",
"''Le pique-nique sa mère''",
"''Faire caca des brindilles ?''",
"''Défonce-moi, défonce-moi, lèche-moi le boule, lèche-moi le boule !!''",
"''Décollaaage...jaaj''",
"L'hilarante série H",
"''Je suis un homme en COLÈRE, 25% de nos jeunes se suicident !''",
"''Moi je suis un Playmobil, en avant les emmerdes !''",
"''Hmm c'est délicieux, cette bonne bite''",
"''Mes frères, AlLaH est avec nous''",
"''Bonsoir Nicolas Dupont-Aignan...bonsooooooooooooooi-''",
"''Je suis français par chaque...centimètre de ma bite, et je l'ai regardée pendant 5 ans...c'est un cap, c'est une péninsule...comment veux-tu que je t'encule''",
"''Tintin qui se masturBAIT dans la salle de bain...''",
"''Madame Castafioootte !''",
"''Par vos propos, par vos propos, popopopopopoooo''",
"''Machine à laver, 40 degrés, j'cuisine des boulettes''",
"''Balécouilles du saucisson, balécouilles moi j'ai Exodia''",
"''Ehhhh salut à tous les amis c'est David Lafarge Pokémon'' (avec la voix qui va avec)",
"''Mon coeur fait oulalala, mon cul fait oulou oulou''",
"''Je suce les zooombiiies''",
"''Je suis Charlie, je suis nazi, je suis noir''",
"''Comme disait le père de la criminalistis criminalistit, bonjour...et j'ajouterai pour ma part : nique ta race !''",
"''NESTOR ! NESCAFÉ !''",
"''Bordel, mais vous êtes Satan !''",
"''J'en ai marre je me casse''",
"''Ahh félicitations Tintin vous êtes un ananas !''",
"''Haha ! C'que j'ai d'la chatte''",
"''Je l'ai appelé le Super colo i o, le Super Connard...et maintenant bande de connards vous allez vivre un moment historique !''",
"''Le son ! Réglez le son !!''",
"''Les Vengeurs, réunissez-vous''",
"Daft Punk - One More Time",
"''Ce soir au menu, poulet rôti avec du riz soufflé au curry''",
"''Pendant que vous finissez toute la guimauve, moi je préfère manger de la merde...j'ai niqué des mèèères !''",
"''Les nichons des suédoises sont réels ?''",
"''PATROOON !!''",
"''Ohhh mais, nique ta soeur !!''",
"''L'Enfer à côté te semblera être une partie de Playmobiiil''",
"''Maxi Kinder Surpriiise''",
"''Vas-y Tag, tiiiiiire !''",
"''Demain c'est dimanche pour tout l'wooong...''",
"''Demain rendez-vous au vieux port, j'te donne mon corps de porc, ce sera hardcore à mort...''",
"''Eh les Tekno, vous êtes nus ?''",
"Gribouille < Charlie < Doliprane",
"''Ça fait beaucoup là non ?''",
"''Allô la Police des polices ? Il m'a tapé !''",
"''Oui allô Bungiiie, j'voulais savoir comment faire pour avoir une connec de pute s'il-vous plaît…Oui alors faut déménager en Amérique, comme tous les ricains et c'est bon…Ok merci du conseil''",
"''Mais comment vous m'Avez trouvé, vous êtes vraiment TRÈS perspicaces''",
"''J'ai glissé chef''",
"La musique de Lavanville",
"''JE MEEEEEURS...tu n'meurs pas du tout''",
"Les sessions Baptême du Feu au lance-grenades pour avoir la flamme bleue sur la MCC",
"''Moureeez dans ma grenade''",
"Blacky qui oublie de lier ses comptes avant de faire les 77h de live Twitch pour avoir l'emblème sur Destiny",
"Le topic JVC ''Je me suis branlé sur Ikora Rey'' de Franckix",
"''Ah tut tut pouet pouet la voilà, la Toto Mobile''",
"''Tut tut fils de pute !''",
"''Gudis 120'000 tonnes...eh bah mon cochon, ça fait 12 fois la Tour Eiffel''",
"''Et voilà 17h il fait nuit, merci l'heure d'hiver hein, merci !''",
"''J'aime la queue''",
"''Gros puceau...gros taré !''",
"''T'as déjà tué une fille ? Non mais j'en connais un qui va souffrir si il continue à me faire maltraiter !''",
"''Haha la loooose, ça prouve qu'ils savent rien sur moiii !''",
"''Faut que je finisse mon anglais''",
"''Quelle heure il est là ?''",
"La légendaire Christmas Card de Blacky",
"''C'est pas possible dans une maisooon de serviiice publiiic''",
"Les cours de boxe thaï de Flogodinus",
"''Ah mais Lio il joue bien en fait''",
"Le BR Blast et le strafe de PGM sur Halo 4",
"Le mode Musquet sur Halo Reach",
"Les batailles de boules de neige sur GTA",
"Les roadtrips en camion sur GTA",
"La Rathalos Airlines sur GTA",
"Biscuit au strip club sur GTA",
"GS Apocalypse et sa bande de 2000 sur GTA",
"GS Apocalypse qui perd ses couilles sur Halo",
"Le légendaire 1v1 Rathalos - Nargacuga sur Halo 4",
"Le mythique duel Franckix - Bézéké sur Paradiso",
"Le lance-concombres",
"Le lance-cornichons",
"Le pistolet à clous du père à Blacky pour tirer sur les poules",
"Le lance-saucissons",
"Le lance-jambon-beurre (ou le lance-sandwich)",
"''L'été c'est vrai que c'est chaud, y toi tu mets la climatisation à fonde...y là SCHLACHT, le pare-brisej il a pas donné''",
"''Loulid il se faisait un sandwich''",
"''Je sais pas pourquoi Loulid, il est toujours disoulé''",
"Les dieux d'Osiris à la Once de Méchanceté",
"Les glaces de Franckix",
"La Baleine Face (''myeuborngyu'')",
"Rathalos qui massacre des cochons sur Minecraft pendant que la mère à Blacky prépare une tarte à la framboise",
"''EH FRANCKIX, ÇA TE DIRAIT DE RETOURNER DES ANIMAUX SUR MINECRAFT ?!''",
"''EXCUSEZ-MOI, JE N'AI PAS COMPRIS CE QUE VOUS AVEZ DIT''",
"Le mythique micro-mouche sur 360",
"Les 5297 fois où Bézéké nous a virés de sa liste d'amis",
"Les armes payantes sur Happy Wars",
"Happy Wars",
"Happy Dungeons",
"''Kitchen in the dungeon''",
"''Oryx ze teïkeun king...his come for you gardiane''",
"Le DLC Roi des Corrompus corrompu de JB",
"Le Drift Violet",
"L'écharpe de Rathalos",
"Le torse nu de JB *q*",
"Le crâne chauve de Bézéké",
"Les dents de sagesse de JB",
"Les rhumes d'été de Rathalos",
"Les funérailles Viking foirées de Bézéké sur Sea of Thieves",
"Francix la perruche sur Sea of Thieves",
"''Eh Style !!''",
"''Eh Francix !!''",
"La voiture chibrax sur GTA",
"''Si je regardais Fairy Tail je passerais ma vie le chibrax à la main''",
"''Je tape ma bite contre la table...ah ça fait un peu mal quand même''",
"Robotector",
"''Para Basilio la escuela es como vacaciones, por que travaja en la mina es mui dificile'' (j'ai fait Allemand LV2 je vous emmerde)",
"''Mikasa es tu casa''",
"''Qu'est-ce qui te mine de charbon''",
"''Toi aussi tu vas te mettre hors-ligne et pas répondre ??!''",
"''Qu'est-ce qui se passe dans l'espace ?''",
"Bézéké et son amour fou pour le lore de Halo 2",
"Bézéké et son amour maladif pour les répliques de Halo 2",
"''Ay ay chef''",
"''Aveuglé PARALYSÉ''",
"''BIENVENUE À REACH !'' (talata talaaa)",
"''Ce qu'il lui faut c'est un suivi psy...avec toi ça fait deux''",
"''Magnifique pas vrai ? Ça mériterait une photo !''",
"''La famille au complet...presque''",
"''ICI LE COMMANDANT DEL RIO''",
"''Nous procédons à la pénétration''",
"''Vous êtes tout seuls Noble''",
"''Ça c'était pour JORGE !''",
"''Ça c'était pour KAT !''",
"''Là je te le rends''",
"''Impossible...pas sur Reach''",
"''Et c'est maintenant qu'il ordonne une opération de démoliTION''",
"''Nik telestekit'' (déso j'ai pas fait Hongrois LV3)",
"Shai nalum, désolé...désolé de quoi ?'' (je parle pas hongrois moi)",
"Les origines nippones de Blacky",
"Les origines juives de Rathalos",
"Lio l'immigré guyanais",
"''Ah ouais Franck de Bruyne comme le joueur de foot''",
"''Didier Football le drogbaleur ?''",
"''Didier Drogba le footballeur ?''",
"''Didididi didjoke''",
"''I eat Mentos !''",
"''Il a fait une Trezezgegz''",
"''Kylian M'Doigté, CR Sexe, N'Zizi''",
"Les fusées Ariane 5 au Relais Cosmique du Cosmodrome",
"Les psions Avengers dans la dernière mission de Destiny 2",
"''Il manque quelque chose à ma viil manque quelque chose à mon cooeeuur, mais moi j'ai beau tenteeer j'ai beau essayeeer mais je n'aurai jamais riennn ! Ton manque est difficile...AÀA supporter, mais je reeeste fort pour toi jerestefortpourmoi C'EST C'QUE TU VOULAAAAAIS !!''",
"''Baaah ok j'veux bien''",
"''Les gars ça vous dit on fait un groupe ?''",
"''Ah salut !'' (avec la voix qui va avec)",
"''Get out of my wayyyyy''",
"''AAAAAAAAAAAAAAAAA-''",
"''Rathalos devient gros''",
"Le rire d'otarie de Rathalos",
"Le rire de toucan de Blacky",
"Le rire de Cyril Hanouna de Franckix",
"Les glaires à JB",
"''La Chouette Zoulman''",
"''FPC Glaireman''",
"''C'est qui ça Grountix''",
"Costume Quest 2",
"''On est en Caveau là on rigole pas''",
"''Ça va pas être possible''",
"''Y a plus d'pont 6 ! Va falloir sauter !!''",
"Steven Tornade, le chasseur de tornades",
"Bear Grylls à Qui Veut Gagner des Millions",
"''Tu peux débrancher la connasse ?''",
"''Les Déchus de la dépression d'Ishtar sur Vénus...ils auraient attaqué la Prison des Vétérans au Récif et capturé un prêtre Archonte...vu la prime de la Reine il doit être puissant...nous devons le retrouver avant qu'ils ne régénèrent totalement son esprit...''",
"''À moins qu'on ne les terrasse, les Déchus continueront de s'acharner sur notre Cité...sous les ruines du Cosmodrome, dans l'ombre d'un vieux vaisseau colonisateur, nous avons repéré le repaire de la maison des Diables, ainsi que le Haut Serviteur qui leur confère leur force...nous devons détruire ce dieu-machine, et renvoyer leurs âmes en Enfer...''",
"''Nous sommes entrés en guerre contre les Cabals de Mars un peu malgré nous, qu'à cela ne tienne, profitons-en pour détruire leurs bases une par une...Valus Tau'urc : d'après nos renseignements il dirige ses sapeurs d'assauts depuis un char impérial à proximité du Rubicon...il est bien protégé mais avec la bonne équipe nous pourrons percer leurs défenses, éliminer ce monstre et libérer Eleuthéria...''",
"''Tiens, vous avez fini par vous réveiller ? Vous avez essayé de traverser la frontière pas vrai ?? Et vous avez foncé tête baissée dans une embuscade des impériaux, tout comme nous…et ce voleur, là''",
"Les petits pains de Skyrim",
"La tourte au horqueur de Skyrim",
"''Wallbang, bien joué''",
"Destiny attente",
"Halo 3 a disparu",
"La config Bâtonnets de Poisson sur Halo 4",
"Les bâtonnets de poisson de Sacred 3",
"Le jogging Décathlon du noich' de Sacred 3",
"''C'est quoi votre jeu préféré après Halo ?''",
"''Vous avez combien d'objets pour gagner des Lumen ??''",
"''AH MAIS IL M'TIRE À LA BLEUE !!''",
"''Congratulations, you won, congratulations you won...''",
"''OUPROUKA''",
"OOF",
"Le service 5 étoiles sur le serveur Pizza Tycoon de Roblox",
"Bézéké qui tryhard Sword Busters 2 sur Roblox",
"Le Sea of Thieves éco+ de Roblox",
"La maison VIP de zZ Élite sur Roblox",
"Le légendaire zZ Élite et ses connaissances obscures en parties perso Halo Reach",
"Le célèbre match FPC VS TsT, avec HF4 Racer en invité de marque",
"Le légendaire match FPC VS HF4",
"''Blacky ===> MA FEMME =D''",
"''HF4 = Homosexuels Français 4''",
"PIZA 4FRO MAGE",
"Le farm de crédits en Grifball sur Halo Reach",
"Les sorcelleries de Bézéké en Forge",
"La map Ewok Party",
"La map MLG Sanctuary v7",
"Les légendaires Raven of Pain et l Uchiwa l (c'est qui ces nonames sans déconner)",
"''Si tu pètes tu peux ramener mon père à la vie''",
"''Cette balle fera 6 trous de balle dans ton père''",
"''C'est du café, ça vient d'Orient''",
"''Au fait t'as le permis toi Blacky ?''",
"''If you think Ronaldo and Messi are not friends watch this vi-''",
"''Si moi j'ai eu mon bac un singe peut l'avoir''",
"Electro = Garou",
"''L'Experto del Gamos''",
"Les Dieux du Stade",
"''Me and the boys in the strikes playlist''",
"''Et allez encore cette satanée méfiance !''",
"''Tu as fait faire ses devoirs à...Diégo ?''",
"''J'aimerais que tu me suces sur le trône de Corinthe'' (tututuuu)",
"''Oscar le film aux 5 oscars''",
"''À mon signal...déchaîne les Enfers''",
"''Maximus...suce''",
"''Steak and cheeeeeeese''",
"''Si Amedy Coulibaly avait reçu le poulet KFC et les bananes en question, il s'en serait sorti indemne...un noir ne peut pas refuser du poulet KFC là, ce n'est que tromperie *tchip*''",
"Le Dernier Voeu de Blacky",
"''Marine Le Pen se rendait à un meeting en ville lorsqu'un noir, Mamadou Bakayoko, sorta une banane de son t-shirt, et la lança sur Marine Le Pen...Marine Le Pen est morte sur le coup''",
"''Dracaufeuj le Pokémon juif''",
"''She looks nice''",
"Les Savathûn de Bézéké sur Rocket League",
"''Vieux débile !''",
"''Akan bouffe des bites !''",
"Le cerveau de Franckix dans le Trône Brisé",
"''Le Trône Brisaaayyy''",
"Hardcore Henry avec le son en décalé de 5 secondes",
"''TIMON !!''",
"''I'm fast as fuck boiii''",
"Le bol de JB",
"JB et sa forte sensibilité artistique pour le film Assassin's Creed",
"''Yeah boiiiiiiiii''",
"''Mon cringe-o-mètre s'affole''",
"''Mon Pokédex m'indique qu'on s'en bat les Pokécouilles''",
"''Je me tyrannosaure''",
"Le frère de Blacky dans le journal de France 3 Limousin",
"''Yamamoto dans mon garage''",
"''Ouais avec ma meuf on est allé à IKEA, et j'peux t'dire que y a pas que les meubles que j'ai démontés !!''",
"''Sakakouille''",
"''C'est bon, c'est good, c'est Gulli Good !''",
"''C'EST GROS CARTOOOOOON''",
"''Les peuples de la galaxie maîtrisent des pouvoirs fantastiques appelés Fluides...leur puissance est telle qu'on a interdit de les utiliser, sauf dans un domaine...un sport devenu le plus spectaculaire de tous : le Galactic Football''",
"''Y en a qui vont me diiire ça sent le vécuuuuu, ça sent la mooouuule, HNNNNNN''",
"Rathalos = Sid de l' ge de Glace",
"Le prénom improbable du vrai Hunter",
"Le prénom improbable de l'oncle de Donald",
"''Toi t'es le faux Hunter''",
"''Kazumi Ninja...select your fighta''",
"''Salon de l'Auto : le jeu vidéo''",
"Le titan Kev Adams de Franckix",
"Les 3 clones de JB",
"Les 43 titans de Rathalos",
"Le succès des slips du Pape dans Assassin's Creed",
"Le film Red Notice avec Ed Sheeran qui chante et Rathalos qui dort",
"''Wow (smoke)''",
"Les GIFs de Skype",
"Les smileys de Skype et les blagues pourries qu'on faisait avec",
"La sonnerie de Skype",
"''2014, les Covenants envahissent la Terre''",
"''Ça c'est ma machine à blinder, et mon canon''",
"La stratégie de l'Ender sur Air Mech Arena",
"Air Mech Arena",
"Charlie Murder",
"''Subadachiii''",
"Les barres de rire devant A Silent Voice (2016 - Drame/Romance)",
"Le truc qu'a dit Lio avant qu'on se pointe tous du doigt à l'infini sur Sea of Thieves et qu'on sait toujours pas ce que c'était",
"''Au s'cours au s'cours, mon bébé il est tout bleu !''",
"''Elle est dispo, moi aussi...j'crois qu'on va se rencontrer grâce à Snap Fuck''",
"''Ahhh t'es contente qu'on se soit rencontrés grâce à Snap Fuck ? Ouaaais…''",
"''Regardez-moi que je puisse voir vos beaux visages''",
"Franckix le roi du X",
"''Calmez-vous !''",
"''J'ai mal...j'ai maAaAAAhl !!''",
"''Ouais attends une seconde...aAaaAAaAAAahHh-''",
"''Ooonly the strongest will survive !!''",
"''GAAARFIELD''",
"Garfield Kart",
"Les tags trop beaux dans Forza Horizon",
"''Justement, c'est con, mais justement''",
"''Albataaar, Albaaatar, parce que tu pisses assiiiiiis...''",
"''Albaaatar, Albaaatar, il a brûlé ta voituuure...''",
"U2 - With or Without You",
"Les concerts au Domaine",
"Les matchs de foot au Domaine",
"''On n'est pas bien avec les jeunes là ?''",
"''Ma qué yé souis italien yé né pas d'honneur''",
"''Regardez-moi ça, ça c'est ma bite après 3 mois de Xanogène et de Nitro XL ! Putain, ma queue est énorme !!''",
"''Je n'ai pas une queue, mais c'est une sacrée bête''",
"Les batailles de vomi sur Sea of Thieves",
"Franckix ou JB : qui a découvert le spring jump en premier ?",
"Ninja Big Bunny ce gros malaise sur pattes",
"''FaZuS Kampus''",
"iSpiteful ce malaise ambulant",
"La meuf à iSpiteful",
"Le ping de Pingy",
"''Michkapikazujun''",
"Le bébé à Michkapi",
"''#HaricotsVerts''",
"JB et son amour sans limite pour Juju Fitcats",
"Ce gros tas de malaise de TiboInShape",
"''Ok les gars c'est carré'' (avec la voix qui va avec)",
"Rathalos le stalker qui connaissait la maison de Blacky sans jamais y être allé",
"Kevin LeFou 117",
"''Venez les gars on va tous sur un jeu''",
"''Le silence mon frère''",
"''Tu es mon ami'' (en rotant)",
"''Oh les gars vous parlez plus là vous êtes tout tristounes'' (après 3 secondes de silence)",
"''Je m'sus...je m'suschm...je m'suis engagé dans une longue route, après avoir mûrement réfléchi, que je vais niquer tout le monde : Marine Le Pen, Jacques Chirac, François Hollande, Alain Juppé, François Fillon, beaucoup d'autres...ah oui et peut-être même vous Delahousse''",
"''David Pulamerde''",
"''Ah...le con''",
"''Ce n'est pas le moment de se désarmer...ce n'est pas le moment de se désaltérer''",
"''Des cadeaux, je chie des cadeaux...je chie des livres...j'ai fait pipi caca haha ÉNORME''",
"''Je suis très très chaud, j'ai envie de retirer mon slip''",
"''Oui oui oui croissant croissant hon hon hon''",
"''J'arrive...vive''",
"''J'ai envie de me Lebron James''",
"Les caleçons Dragonball de Franckix",
"''Ahhhh...pas mal''",
"''Allez viens Marcel, on s'casse''",
"''Bah elle est où Sabine ? D'habitude elle garde toujours les pieds sur Terre...oh bah, nique sa mère''",
"''Hum hum hum...tu es con''",
"''La jouj des faaf''",
"''Un instant...je pisse''",
"''Bonsoir les enfants, je suis tout nu...Nounours est immonnndeuh…(Ça c'est vrai) Je suis le marchand de caaameuh, c'est d'la bonne, Nounours viens dans mon liiit...et nous partouzons joyeusement, et tu me suceuh, je chaaante comme un pieeed...c'est l'anarchiiie...''",
"''À nous deux mon gaillard''",
"''Méfie-toi de lui Sangoku il est daaangereux...''",
"''Oh bah ça oh bah ça ohhh bahhh çaaa...''",
"''Bonjour ? Bonjour ?? Bonjouuuj''",
"''Bonsaus''",
"''Il doit se joindre à nous, il doit rejoindre les guerriers de l'espaaace...saaas...''",
"''Ça te dirait d'aller te faire dérouiller un peu dans l'espace ?''",
"''Il va nous transformer en galette des rois''",
"Guts Pingouin (ooohhh)",
"''Ça ne va pas ? Tu veux un pansement, du Mercurochrome ??''",
"''Yakon le monstre des monstres ! On raconte qu'il peut tuer 14 loups d'un seul coup de poing !!''",
"''C'est une très jolie histoire ! Si vous ne la connaissez pas les enfants, demandez à vos parents de vous la rafonter, histoire de bien mieux se faire chier ! Nique la police !''",
"La manette chromée ''#1 Ninja FR'' de JB",
"''Nosaure !''",
"''Sucepute !''",
"''Oh putain ils sont trop bons c't'année !''",
"''Je voudrais quE TU Te rappeeeeelles !!''",
"Le Japanese Stare",
"''Ho ho, kimono banzaï sushi !''",
"''Alors là t'as fait l'erreur de ta vie Nagazaki''",
"''Et alors quoi tu t'attendais à voir la famille Addams t'es déçu ?''",
"Les rubans attrape-mouches",
"''Et là je baise le camerounéen''",
"''Le Christ Comique''",
"''Waaah qu'est-ce que c'est qu'ce truc là euh…''",
"''AH INSERT ! INSERT LE TRUC EN FAIT DE LA SOURIS ! Pour savoir si je triche, mais non je triche pas moi ! Ah…le p'tit malin ! ''",
"''Ah un zèbre !?''",
"Le zèbre qui chie"
"''Reçu reçu reçu reçu reçu…''",
"''Qu'est-ce que vous regardez…vous voulez une arme ?''",
"''J'ai l'air d'une borne de rechargement ou quoi ?!''",
"''VÉRONICA !! PARLEZ-MOI !''",
"''Woh ! C'est Madrid en face ! Tu joues pas contre Pontault-Combault ou euuuh Draveil ! Ouiii monsieur bonjour ?''",
"''Oui euh toi je sais que tu t'appelles Pierre euh…''",
"''Ouais ouais ouais, on les a eus, ouais ouais ouaaaiy...''",
"''Sylvain Dudrift''",
"''Dans ma chambre en plus hein...suus hein''",
"Le t-shirt Angry Birds Yoda collector",
"''Alors peut-être !!?''",
"Le malaise insoutenable des gens qui téléchargeaient pas Forge Island (y avait aussi ceux qui avait le contrôle parental qui les empêchait de jouer sur n'importe quelle map forgée)",
"''T'as pété Marie-Ange !''",
"''MARC !''",
"''Le match entre Chantal et ma bite, en images...''",
"Succès déverrouillé : vous avez trouvé l'Easter-Egg caché au fin fond du lore de Dinosaure, on vous l'avait dit que c'était bien le lore !",
"Succès déverrouillé : nan rien XD",
"''Le prochain Halo !''",
"''Allez, salut tout le monde, à la prochaine, PEACE !'' + Uppermost - Flashback en fond",
"''Et vive Halo !!''",
"''AXIOS !! Heeeeeeeeeee hiiiiiiiiiiii heeeeeeaaaaa hooo...''",
"Ersell de Halo.fr",
"Les machinimas de Spartantealc",
"Le gâteau au yaourt de Spartantealc",
"Eldarions et son cancer en phase terminale",
"Nexus le Halo pro player à l'AR",
"''ATTENTION AUX CRISTAUX !!''",
"''Matière toxique''",
"''Ninja Aypierre''",
"''Oh putééé, prends ça connard !! Laissez-moi du zombie, les potes !''",
"''Ah pourquoi on est pas sur One''",
"La musique de Forward Unto Dawn avec la meuf qui chante là",
"Le vomi de Lasky dans Forward Unto Dawn",
"''C'est mal connaître mes nouveaux pouvwaaars...''",
"''You underestimate my POOOwer...''",
"''Tieeens entre tes mains ton intestiiin, mets le voile dès ce matinnn, allah akbar''",
"''Comme un hooomme, sois violent avec ta femme !''",
"''Toi qui crois que ta mère est constipée, tu te doutes pas que je l'ai sodomisée''",
"''Tout le monde le goûte''",
"''Quand ils l'ont enterrééé, sa baguette s'est casséééeee, c'était triiisteuh...''",
"''ZGEG NOW !!''",
"Le trailer de Halo Infinite dans le désert avec le poncho de Master Chief",
"Le nécromancien de Dol Guldur",
"''Des vibro-droïdes dans le cul''",
"Le Nécromanticum",
"''Amadeus Sanctus''",
"La perk Maleficius Maleficarum",
"''Creuseeez Dwemers, creusez, dans les profondeuuurs...''",
"''Garfield you fat cat, you are so big and fat, why are you so fat !''",
"''You're going into orbit, you stupid mutt''",
"''Dans orbite y a or''",
"''J'avais l'impression de me faire sodomiser par un noir avec son gros gourdin ti bordel de merde''",
"''J'avais mon PETIT CUL qu'était tout dilaté''",
"''Ça faisait ahgh drôle''",
"Le mec de la gestapo dont on cachait Franckix à chaque fois qu'il venait ce gros malaise là",
"''Nan mais franchement pauvre abruti va, t'es vraiment la dernière des merdes hein !''",
"''Holy quickscope FaZe''",
"''Call of du Tipp-eeex''",
"''Cesse de dire cees, il n'existe aucun lien entre nous, mon nom est San Gohan, mon nom est SAUS, mon nom est Ku, Sangoku''",
"''Pourquoi m'appelles-tu petit frère ?''",
"''L'île noire est une île noire''",
"''CAPITAINE ! Fermez votre fenêtre !''",
"''Partez !...Allez !...''",
"''Mes hommages madame je suis autiiiste''",
"''Il m'a assommé et il m'a assommé, et je le reconnais c'est ma soeur !''",
"''Oh Dupont et Dupont et Dupont…BONJOUR MADAME !''",
"''Oh oh, ça sent bon !''",
"''J'installe une sono d'enfer dans mon cul !''",
"Les scripts magique de Franckix (dont celui-là)",
"''LE SCRIPTADOS !!''",
"''Il a un Crrrooonus !''",
"''C'est toi mon petit coeur ?''",
"''Mon nom est savon…moi je m'appelle bêtise !''",
"''Ah ! Mon fiooonnn !!''",
"''Oh ha ! C'est Harry ! Je vais lui demander de m'épouser !''",
"''T'es con, fils de pute !''",
"La Sakura sex scene",
"La scène de cul de Master Chief dans la série Halo avec Cortana la cuck qui regarde, comme dans les jeux",
"La voix horrible de Ehroar",
"Halo : La Collection Le Major",
"''We are…the weekend warriors !'' (tfutututuduuu tuduuu tuduuu tu tu tuduuu tududuuu)",
"''Coucou Blacky''",
"''Coucou Electro''",
"Mattéo les fenêtres et son jumeau Mattéo les volets coulissants",
"''Halo SF''",
"Le sublime TCAOSierra117",
"Fataljo59, le cousin à Franckix",
"''Je vais te ragdoule''",
"''Reviens là j'vais t'manger !''",
"''Reviens ici batard !''",
"Les lunettes de Rathalos",
"La musique des clipshots de Halo QG",
"Les extraits moisis de Halo QG",
"Croptafilsdoryx",
"FPC Vendetta / Legendary, l'allié inconnu",
"''Le Grand Mystic''",
"Ceixe - Tueur",
"Franckix - Tueur",
"''Toujours le MVP et dans le top médailles !''",
"''T'es mon ami et bien plus encore !''",
"''Judoboyyy, en fait ça c'est du karatééé, je me suis complètement plantééé, et on m'a virééé''",
"La grenade ananas de Halo Pafinite",
"Les oreilles de chat de Halo Pafinite",
"Les flammes.jpeg de Halo Pafinite",
"Les micros devant le nez",
"''Il a la connec' mec !''",
"Les infâmes mexicains sur Halo",
"''Sur mon écran je voyais pas ça''",
"Le légendaire DSG Milo et son superbe rap sur Halooo 2, Halooo 2",
"Le petit cul nu de Master Chief dans la série Halo, comme dans les jeux",
"''Vous êtes de la télé ? Alors j'ai des nouvelles qui pourraient vous être d'un certain euh…intérêt !''",
"''Merde les dinosaures ont envahi l'île, qu'est-ce qu'on fait ? Bah on empile les caisses !''",
"''C'est con !''",
"''Bonsoir à tooooous, quel bonheur de vous retrouver direct, ici en direct, Direct Assurances, pour vivre ensemble avec vous ce soir, cette magnifique saucisse''",
"''J'étais en train de tirer mon énorme râteau''",
"''Un gamin de 15 aaans, c'est de la viande à manger…un boeuf, c'est  de la viande à manger…Morandini c'est de la viande à chier !''",
"''J'ai fait une émission pour les enfants qui s'appelait ''Comment niquer des enfants'', on nique des gamins tous les soirs !''",
"''Les sauuuts de ce jeuuu sont horriiibles ce jeu est affreux…''",
"''Oh bah la prochaine fois j'amènerai le chien lui au moins il y arrive !''",
"''Eh m'sieur Grenier c'est vous qu'avez cassé le mur ?''",
"''J'vais pas y aller en rampant merde''",
"''Tu tu tu tu'' (c'est le bruit du lance-plasma de Halo Reach)",
"''Les sauts…les sauuuts…les saucisses *bulubulu*''",
"''J'ai perdu ma boule et maintenant moi aussi je perds la boooule !!''",
"''Les balles du dragon ?!''",
"''Un point avec un t c'est ça .''",
"''Eh salut Gary !'' (avec la voix de Bob l'Éponge évidemment)",
"''OOOOOHHH qui va venir niquer ta mère !!''",
"''YOOOOOUUU'RE HEEEEERE THERE'S NOOOOOOOTHING I FEAAAAAR !!''",
"HOHOHOOOOOOOOOO HOHOHOHOOOOOO...''",
"Jean-Jacques Goldman - Là-bas (Cover by Blacky & Rathalos)",
"Le générique de Corneil et Bernie",
"''Ça ça fait danser les rats ça !''",
"''Capitaine *snif* y a Machicouli qui s'est fait caca dessus *snif*'' (voix de La Sardine)",
"''Oh allez même le gardien de son coeur il l'aurait arrêtée celle-là !''",
"''*fioufiou* Sauce ! *fioufiou*''",
"''Snons''",
"''Jeej jaaj saus''",
"''Suus''",
"''Je vais la preeendre par derrièèère, je vais lui défoncer le cuuul, et y aura plus grand chose à faiiire, son anus est foutu...'' (avec la mélodie qui va avec évidemment)",
"''Cette nuit, j'ai sorti mon zizi...je l'aiii mis sur ta têêêteuh'' (avec la mélodie qui va avec cela va de soi",
"''Je suis l'homme cacaaaaa cacacacaca !''",
"Mint Blitz ce gros malaise vagal",
"''Get fucked''",
"''Blacked''",
"''Alicia Keys…c'est qui''",
"Le sketch inédit du Woop Gang",
"''Ahgh qu'est-ce que tu fais c'est moi c'est Végétaaghg''",
"La voix de Gremlins de Blacky",
"''Saaalut grosse saaalope…oh ? Squuezie ?''",
"''Tu viens de la planète...Veujeuta...tu es un guerrier Séyan...cccomme moi...''",
"''Pour faire apparaître ma maison il faut d'abord dire rirnomanofil...''",
"''Avec des minis zizis !!''",
"La voix de Scooby Doo",
"''You must be Mr Bond…No !...You must be Mr Boba Fett…No !...You must be Mr Bob Omb…No !''",
"La config Bumper Jumper de tous les Halo",
"''Batman s'est fait niquer sa mère !''"
"''Ferme ta gueule Robin !''",
"''C'est le traditionnel gâteau moldave, et maintenant je vais couper vos bites''",
"''Cheese knife !''",
"''Insane !''",
"''Malaise Man''",
"''Anal Bray et Raspoop''",
"Le T4 BABE, MYLF, TEEN, LESB sur Halo Reach",
"''Quoi sortir du camion ? Moi ? Par ce froid ? Qucaquoi moi ? Sorsorsortir du camion ? Moi ? Par ce froid ?''",
"''C'est amusant, quand j'étais petit les remparts et les tours des impériaux me donnaient un sentiment de sécurité…''",
"''La chatte qu'il a, LA CHAAATTE !!''",
"''This is my peepee (peepee), this is my peepee (peepee), this is my peepee this is myyy peepee…''",
"''Daaaaans ton espaaace virtuel, tu aaaaapparais tellement réel''",
"''Gotego peeeeeeepeeeee…have a seat…have a seaaat in my peeeeee…''",
"''Oh, des poils de chatte…ah mais oui c'est les miens, j'les ai coupés l'année passée…''",
"''Oh mon dieu, ils m'ont pris en embuscade…je vais envoyer la cavalerie voir ce qui s'passe…je vais prendre la formation ciseau, pour leur couper les fesses''",
"Le black qui fait semblait de jouer au JRPG mobile pour la pub",
"''Clash of Kings…restez proches de vos alliés, mais encore plus de vos ennemis dans Clash of Kings !''",
"''CLASH ! ROYAAALE ! Des combats contre tout le monde ! Des duels en temps réels !''",
"''Les gars j'suis un bot''",
"''THE CITY'S ON FIIIRE !!''",
"Theory of a Deadman - Lowlife",
"Les passes à l'infini en Ricochet",
"Le farm de points en sautant en mangouste pendant toute la game en Warzone sur Halo 5",
"Le mythique Sparrow Flying",
"Le Sparrow Flying mais de JB",
"''LA PUISSANCE DU MERC''",
"Les Dicci noires de Rathalos sur Rocket League",
"Les casquettes McDo de Blacky sur Rocket League",
"''Polo la classe''",
"La saucisse de Monster Hunter",
"''Ahh la programmation c'est merveilleux, et sinon, tu aimes les films de gladiateurs ?''",
"''Tu as déjà vu un monsieur tout nu ?''"
"La Ouiche Loraine",
"''Parle-moi un peu de Georges Abitbol''",
"''Enculé d'ta race !''"
"''Oh merde, j'ai jamais pu blairer les nazis…''",
"''On va manger DES CHIPS, t'entends ?! DES CHIPS !! Qu'est-ce t'as tu fais la trooonche ou quoi, t'es pas content quand je te dis qu'on va manger des chips ??''",
"''Quand je pense que tu seur sirpresseur sirpresseur !''",
"''Eh oui, j'ai une passion pour Beethoven''",
"''Bite au vent''",
"''Avec ma main droite, je résous une équation, et avec ma main gauche, je prends une chips QUE JE MANGE !''",
"Le sombre passé de Rathalos sur Blablaland",
"''Ah are you ready to die hum, Shinigami Eyes, à la one again bistouflaille, the Shinigami Eyes''",
"''FLYING FOREEEEEVEEER !!''",
"La chanson Angel Wings de Rocket League",
"''LADY ! HEAR ME TONIGHT !!''",
"Les CD de Minecraft",
"La bite en poterie de TiboInShape",
"''JOOOOOOOOOJOSHHH jump in the caac (yeah)''",
"''ODST PRÊTS''",
"''Mais d'où alors, d'où pouvons-nous activer les autres anneaux dans ce cas ?''",
"Le Titre Légende",
"La Super Cellule Saucisse aka le fusil d'assaut de la mafia",
"''SYLOK, THE DEFILED !!''",
"''KEKSIS, THE BETRAYED !!''",
"Le pistolet de James Bond, pour James Bondiser les mobs",
"''Nicaragua, nicaragua, nicaragua...''",
"La bêtise des gens qui nous appelaient FPC alors qu'on était genre 3 avec FPC dans le nom",
"''Les KFR Girls elles sont mauvaises en vrai, elles sont KFR juste parce que c'est des filles''",
"''Dino Train (Dino Train), Dino Train (Dino Train), on va plus loinnnnn (loin loin loin loinnn) en Dino Train !''",
"''Y a pas que d'la bière au beurre dans vot' cave monsieur Potter''",
"''Harry Pot-de-Fleur''",
"''Harry Pot-de-Beurre''",
"''Harry Shitposteur''",
"''Harry a un rictus !''",
"''Regardez-moi ! REGARDEZ-MOI ! Harry Potter le narcissique...''",
"Le jogging Décathlon de Sangohan dans Dragonball Super",
"''COMMENT OSES-TU...FRAPPER MA BULMAAAAAAA''",
"''BadaBOUM !!''",
"''ATTENTIOOONNN !''",
"''KaaaaaaaaaaaaaaaaméhaméHAAAAAAAAAA''",
"''RAYON MAGIIIIIQUE !!''"
"''Thanus''",
"''Il est complètement zinzin celui-là''",
"''C'est clownesque''",
"''Il est complètement imbibé celui-ci''",
"''ÉCRIS L'HISTWAAAAAAAAAAAAHAHARE !! DANS MA MÉMWAAAAAAAAHAHAHAAAAAHAHAAARE !! MAIS N'ÉCRIS JAAAMAIS LA FIN ! (mais n'écris jaaamais la fin) Parce que j'suis mort''",
"''Du coup j'meurs''",
"''Je plonge, je remonte à la surface, et là, plus de maillot !! J'suis à poil ! Au milieu des gens qui nagent...jaaj''",
"Le thème de Halo",
"''Tant pis je meurs''",
"''Saluuut c'est Johnny''",
"''Wake the fuck up samurai''",
"''S-S-S-Samurai Champloo''",
"''Isis-is-i-ii-isis-is''",
"''Liche liche moi la babine''",
"''JAAAPOOON !!''",
"La future coloc de ouf au Japon, ça va être trop bien ^w^ Le Japon meilleur pays ~desu",
"''C'est mon fils, sif''",
"''Le Cillit Gangbang, contre les tâches et le caca''",
"''Bordel de meeerde''",
"''MEEEEERDE J'T'EMMERDE !''",
"''Fait chier de merde '' (avec l'accent qui va avec)",
"''Fait chier la bite''",
"''QuI vEuT dU rÉgLiSsE ?!''",
"''Oh putain Biscuit le logo FWC sur le casque''",
"''Taking you to school''",
"La musique de Rocket League qui fait paneupaneupaneupeeeuuu",
"''EREN JÄÄÄGER !!''",
"''LIGHT YYYAGAMI !!''",
"''Tatakae, tatakae, tatakae, tatakae...''",
"''ZZZOU !!''",
"''Vous n'êtes que des traîîîtres !!''",
"L'arc Infinité I du père à Blacky",
"Les 1959258 flèches Dwemer pour monter le Forgeage sur Skyrim",
"Les dagues de Fer de JB sur Skyrim",
"Franckix en slip sur Skyrim",
"La mythique serviette de Franckix",
"''Ce mec il est trop beauuu, ce mec il est trop stylééé''",
"Playmobil Pirates",
"Playmobil Top Agent",
"LEGO Battle",
"LEGO Star Wars : La Saga Complète",
"Le cri de Yoda dans LEGO Star Wars",
"Les ewoks qui jettent du caca dans LEGO Star Wars",
"Le niveau bonus ''LEGO City'' dans LEGO Star Wars",
"''A man has fallen into the river in LEGO City...HEYYY''",
"''1 chance sur 4 m8''",
"Le sniper vert avec un aim assist négatif sur D1",
"La mythkque ''Kotchkov'' de Destiny",
"Franckix = Hacker Man",
"L'emblème Pogba sur D1",
"Les 57 comptes secondaires de Franckix",
"''Écoutez, dans le Panthéon de mes valeurs y a un mot très important qu'est la suce''",
"''Hentai rape''",
"Petit rappel que la commu Xbox préfère les lesbiennes, la commu PS préfère les MILF, et la commu Nintendo préfère les hentai...voilà, ''faut l'savoir hein''",
"''Écoutez monsieur Seb...''",
"Nightcore - Sous le Vent",
"''PANTSUUU''",
"''YEAAAH...POOOOOOOOOO''",
"''My BOdy bruuuised, she GOT me with'' (avec la voix évidemment)(c'est les vraies paroles au fait)",
"''Tu n'as pas changé depuis la dernière fois que j't'ai vu p'tit CHIEN''",
"''Kriliiiiiiinlirk !''",
"''C'est la fête dans mon slip !''",
"''Et bah on vous emmerde Annie''",
"Les bonbons au miel sur Skyrim",
"Les orteils de géant sur Skyrim",
"Le fromage de mammouth sur Skyrim",
"Le Mammouth de Halo 4",
"''MEULE !''",
"Le succès des crédits sur Harm's Way",
"Toy Soldier Cold War",
"Le générique de Tom et Sheenah",
"''AMI DES MASSAÏÏÏ''",
"''Et moi t'as vu ? J'ai construit un pont, ça m'a pris quoi...10 minutes ? 11 à tout péter''",
"Kronk",
"L'auto bronzant des images de joueur sur Rocket League",
"''L'artiste maestro, tu connais l'blase, toutes tes copines te diront qu'c'est la base''",
"L'africain ou je sais plus quoi qui sait utiliser un M16 dans le Tomb Raider Games With Gold là",
"''So you don't CRY FOR MEEEEE, SEWA SHINADOOO, KOOONASHIWAAADA !! And I cry for youuuuu, IBAAA SHINADOOO, IJEEEEE, TAGUEUUUUUULE...CRY FOR MEEEEEEEEEEEEEEEEE WAHAHAHOUWAAAAAAAAAAAA-''",
"Le barbeuc de Messi et Ronaldo",
"Armin",
"Le caporal-chef Livaï",
"''T'es défoncé ? Nonnn sergent-chef''",
"''Est-ce que j'ai éteint le four…''",
"Le volley sur Rocket League, lol",
"Les hologrammes qui peuvent t-bag sur Halo 4",
"''Pika pika pika dance !''",
"Les Mantis qui peuvent t-bag sur Halo 4''",
"''Je vais te /gouv''",
"''Ah bah c'est bon alooors''",
"''On peut donc dire que le salami est votre seul ami''",
"''Cuir, tanner, vanne de merde''",
"''Dominic Pucelle''",
"''Ettt c'est le gentil le méchant, il balance le méchant dans la mer, il est très gentil le gentil, il est très méchant le méchant, et ça je sais pas si c'est mère ou si c'est sa meuf je sais pas si c'est sa mère ou si c'est sa meuf...''",
"''IL EST CONTENT GAËTAN !''",
"''GNEEE G TEAU IL EST CONTENT LE DAUPHINNN''",
"''Gnn REGARDEEEY, chuis trrrop fort putain''",
"Le djembé de la mère à Rathalos",
"Le gros pif du gars dans A Way Out",
"Vikingdome",
"''This is my cum, this is my cum''",
"Imagine Dragons - Demons",
"''Ça dépasse l'entendement !''",
"''Ehhh bondour eh !''",
"''Je vais te chicote !''",
"''Hellooo I'm Johnnyyy, good afternooooon !''",
"''Je suis sous ton liiit''",
"''fffffffpokémonfffffdracaufeuffffffffpikachuffff...''",
"La Team Légumes",
"Revêtement légendaire : Le Pendu",
"Revêtement légendaire : Revenant",
"Revêtement légendaire : Acier Acerbe",
"''Ça va Stromae ? Ouais'' (la suite on la connaît, grosse flemme)",
"''Et toi, tu fais l'malin parc'que tu t'es branlé ?! Mais revieeens boloooss !! Si papa nique plus maman, c'est parce que papa nique mamie, tiens !''",
"''Qu'est-ce que vous avez à m'regarder comme un macaque, donnez-moi un bébé sinnnge, il s'ra fooormidableuh''",
"''Où es ton steak haché ? Ça doit, faire au moins 1000 fois qu'on a, doigté nos fesses, HEY'' (tfudututu tuuu)",
"''Toujours la banane, toujours debout ! Je m'suis tapééé vos soeuuurs''",
"Olivier Giroud dans Black Ops 3",
"La perk Fer à Cheval de D1",
"La perk Grenadier de D1",
"Le malaise corrosif des gens qui vidaient la moitié de leur chargeur pour avoir les dégâts de Verre à Moitié Plein (ou Vide je sais plus) direct",
"''Giroud il est moins fort que Benzema parce qu'il met presque jamais de buts, même Payet il est plus fort parce qu'il met plein de buts lui''",
"''Acerb''",
"''Salut Ceize''",
"''Panduh''",
"''Laure Manaudou...Laure Nazi''",
"''Oh ! Un Élékable ! (Baylando Baylando…)''",
"Les dialogues de Johnson dans le désordre quand tu allais trop vite dans Alliance Covenant sur Halo 3, avec la radio qui fait frrrt et tout le bordel là",
"L'assaut du Chant de Savathûn sur D2",
"L'assaut de la Corrompute sur D2",
"Le rage quit instantané sur les assauts des Flagellateurs Psions de D1 et l'Exode Noir et l'Antre Creux de D2",
"La fois où on avait croisé Franckix qui faisait des tricks en passereau en patrouille au tout début d'un assaut Omnigul sur D1",
"''Il était trop chaud, il voulait faire un trickshot sa mère…allons manger du saucisson Justin Bridou maintenant, avant qu'il ne soit périmé''",
"''Je suis Alain Bridou, frère de Justin Bridou''",
"''On vous suce la bite général Kénobi ! Nan arrête tu en fais trop !''",
"''Maître, le vaisseau du général Grievous est juste devant nous, c'est celui qui grouille d'hémorroïdes !''",
"La bataille de Coruscant mais sur LEGO Star Wars", 
"''Nan mais laissez-moi, nan mais laissez-moooi...manger ma banane ! Nan mais laissez-moi, nan mais laissez-moooi...manger ma banane tout nu suuur la plaaage...''",
"''Tu m'fais pas peur, moi j'ai dejà escaladé le Mont Blanc''",
"La CS Escalade",
"La CS Anti-Brume",
"Spiritomb",
"Les vaisseaux Super U",
"Les respawns affreux en coop sur Halo CE",
"''RDV JDO''",
"La mosquée de Sucy-en-Brie",
"L'église Saint-Martin de Bussière-Galant et de Sucy-en-Brie",
"La timeline où Johnson devient un parasite dans Halo 3",
"Le sticker Snap de Cell qui vomit du speuspeu",
"Le sticker Snap de Bikini qui ressemble à Sarkozy quand il dit ''Mais vous fumez monsieur''",
"Les stickers Snap de Totoro, Chihiro et Cloverfield",
"Cloverfield",
"''Mais vous fumez monsieur''",
"JBuilder",
"Jb (hunter 13)",
"''Tu veux une fleur ? :)''",
"''AWOWOWOWOWOWOWOWOWOWOWA... AWOWOWOWOWOWOW...WOWOWOW...''",
"''Amandine c'est à vous que revient l'honneur de démarrer puisqueee vous êtes faible''",
"''Quel animal de la fesse ? Un lapin''",
"''Ouais...ouaiw...ferme-la pour voir, ah ouais c'est mieux comme ça''",
"''Laurence Ferrari j'aimerais bien la conduiiire, et la mettre en pôle position dans un hôtel FORMULE 1''",
"''PÔLE POSITIONNN, QUI M'AMÈNE DIX GLAÇOOONNNS !!''",
"''La vie de ma mère change pas de sujet putain''",
"''Sans doute en fait et jeje ejej...suus''",
"''Écoutez, je veux pas encore avoir l'air de vous contredire mais niiique ta mère''",
"''Aujourd'hui ta mère''",
"''Ta mère !'' (voix de merde de Bézéké)",
"''Qui a le temps aujourd'hui de faire des confitures ?''",
"''Je me demande ce que Ganon est en train de faire...''",
"''Mon petit, cette paix est ce pourquoi luttent tous les vrais guerriers...''",
"''Et flashhh, me voilà !''",
"Pythagore et toutes les lois de la physique en sueur sur Rocket League",
"''La Bat-Lime est notre dernièèère chance !''"
"''Saperlipopette un ver de terre géant !''",
"''Enfer et damnation, c'est Wonder Woman et les jumeaux !''",
"''Scrogneugneu, toute la ville est en train de s'affaisser dans l'océan !''",
"''Super, j'ai hâte de bombarder les Dodongo !''",
"''On va niquer ce soir !''",
"''Filme mes pieds ! Les Clarksss !!''",
"''Vous êtes sur D8 et vous allez regardeeer ma bite !''",
"''Que tu es bécasse''",
"''Le Maillon Faible, le''",
"''Émiliennn suce''",
"''Sébastien, 25 femmes (SALAAAUD !!)''",
"''PHILLIIIIIPE, JE SAIS OÙ TU T'CACHES, VIENS ICI SALE ENCULÉ !! TA GUEUUULE, VIENS ICI SALE ENCULÉ ! SALAAAUD !!''",
"Le paradoxe de l'axe Z",
"''Une action un but''",
"''El patator''",
"''J'ai kebabz''",
"La voiture sapin de Noël qui miaule sur Rocket League, insupportable",
"''Sophie, quel mot ? Beu bah beu''",
"''Yeah bag him bro bag him ! It's a New Light player ! Look at him bro look at him, he,s a New Light player, he has blue gear and he's BAGGING !!''",
"La veilleuse Picsou de Blacky",
"''Eh bah dis donc...t'en as mis du EHHH''",
"''Get the fuck out of my face bro''",
"''J O U J : JOUJ''",
"''I'm sorryyyyy''",
"Les singes, gorilles, babouins et autres monkass en ligne",
"''You freaking rhino ! Go back to the fucking ZOO man !!''",
"Le légendaire ToxicBolt",
"''Il est de retour !! L'ange s'est envolé !''",
"''Crucifié !''",
"Le gameplay de l'E3",
"La spéciale sur Rocket League",
"''Il est braindead lui''",
"''Fifty fifty God''",
"''Ah okkk ça y est j'ai compriiis''",
"''Ah voilà lui il est parti voir mamie dans les tribunes''",
"Simularbre",
"Les TTV dans le GT",
"''UnE hEuRe De CoLlE !!''",
"''Couteaaau !''",
"La map Xenon Castle",
"Les maps Assassinarion Tower",
"''Et toujours sans l'savoir...''",
"Le bug de Rocket League où le jeu était fluide que quand tu te mettais sur le dos",
"Le bug sur Halo Reach où on avait tous l'armure de base",
"Les bugs de chunks",
"''Mon nom est Tranks, je viens de 20 ans dans le futur''",
"''Ouiii donnez-moi une chambre pour moi et ces 2 jeunes enfants s'il-vous-plaît''",
"''J'invoque Mon Grand Père le Maudit !''",
"''C'est torrible''",
"Le Monde des Toons",
"Le deck Renoncé de Noobi",
"Le Golem de Lave",
"''Mécanique Annntique !''",
"''Biscuit un jour..!''",
"''Prends ça fumier !!''",
"''Attendez j'm'asseois un peu là''",
"Les tutos Dark Souls de Biscuit",
"''Bien évidemment, je n'oublie pas de remplir mon attestation avant d'aller faire mes courses, et j'applaudis bien les soignants aux fenêtres à 20h''",
"''Ça va...ÇA VAX !''",
"''Tiens tiens tiens...''",
"''Voilà j'ai BU mon café en terrasse !''",
"''Voilà je l'ai le pass sanitaire, on me l'a demandé tout de suite, le serveur me l'a demandé pour scanner le...le QR codeuh''",
"''Si c'est le seul moyen pour enrayer l'épidémie moi j'dis allons-y quoi !''",
"''Mon nom est Garlic, garde à vous''",
"''Anthox Colle-à-Bois",
"Les Tortues Ninja sur Minecraft",
"Les îles flottantes de Rathalos sur Minecraft",
"''Houbaaa houbaaa Marsupilami HINHINNN''",
"Le Flipper Waluigi",
"Le Quartier Delfino",
"La musique de Mario 3D Land",
"La musique de Mario Kart Double Dash",
"''Waaah QI de 143''",
"''Ton absonce m'omprisonne, ton nom sinon je m'abondonne, j'ai tonté d'appeleeer''",
"''Audi R8, Au-Au-Audi R8...si t'as pas d'amis prends un Curly !''",
"''J'roule en V12, j'ai l'humouuur à Jameeel Debbouze''",
"Le mec qui peint en criant sur sa peinture",
"Le mec qui mange sa cigarette allumée",
"Le gros coréen terrifiant qui engloutit sa soupe ainsi que tout le reste de l'univers",
"''Moi à 3 ans je bouffais encore du sable''",
"La fenêtre cassée du coréen torse nu",
"Quand tu as envie de faire caca mais que t'y vas pas tout de suite parce que c'est stylé un peu",
"Les Olive & Tom sur Rocket League",
"''LES NOMBRES MASON ! QUE VEULENT-ILS DIRE !!''",
"''TU ÉTAIS À VORKUTA MASON, TU AS RENCONTRÉ VIKTOR REZNOV !!''",
"''Il s'appelle Robert Paulson''",
"Le vieux qui chante dans sa douche avec sa mousse à raser partout sur la tête",
"Ah ! T'as failli avoir l'Easter Egg légendo-mythique ultime au taux de drop archi faible, ''alors qu'en fait pas du tout !''",
"''Début des années 2000, tous les gamins s'appellent Kevin'' (avec la voix évidemment)",
"''No time to lose, we GOT to move, show me the wayyy''",
"Halo 2 - Blow Me Away",
"''Morsmordre !!''",
"''Hatis temporuuus !!''",
"''La loterie de l'existence...sans''",
"''Ah ok c'est ce genre de match''",
"''Saved by the kipa !''",
"''Get shit on''"
"''Ça va devenir vrai dans cette pièce pour quelques instants...et voilà, ma chaîne touche à mon pénis''",
"''C'est la chambre que j'construis pour faire la guerre des étoiles tu vois''",
"''C'est tendu sur la ZA !''",
"''Achnachnevach''",
"Les vasards sur Skyrim qui t'empêchaient de te TP ces batards",
"''C'est toi qu'on appelle Vash the Stampede ??''",
"Le jus orange des pizzas",
"Le génie civil de Franckix quand il s'agit de faire des trucs parfaitement inutiles (notamment ce merveilleux bot)",
"''Shish ! Sonson ! Enbi Mayonnaizé !!'' (Japonais LV8)",
"''J't'envoie au front toi''",
"L'opening d'animé ou je sais plus trop quoi avec le mec qui crie à l'infini là",
"L'opening d'animé ou un ending je sais plus trop, bref la musique jap où à un moment le gars dit caca",
"''Kaka ! Yayayaaaya, yayayaaaya, ehh ehh ehhh, yayayaaaya...''",
"''Bigflo et Olive''",
"''Kekkaishi partout''",
"''La pressionnn je sais qu'tu la ressennns...''",
"''La gre de l'impossible !''",
"''Stève Mandanda''",
"''J'ai le Sum 41''",
"''Skrr skrr gros fils de pute !''",
"''Always has been''",
"''Ça sent la mooort ici''",
"''Va tout seul''",
"''Je m'suis Dragonball Tashitsu''",
"''J'ai scratché scrachscratché...j'ai accidenté le drone''",
"''Imagine''",
"Le chien-fantôme gay dans Kekkaishi (Madarao, si jamais...), et même que son ennemi juré, dont il est aussi un peu amoureux je crois, il s'appelle Kouya...comme les couilles...''oh bah si c'est...c'est rigolooo''",
"''Oh ! Le menu il fait bloub bloub...comme dans l'eau...c'est...rigolo ?''",
"''Alors euuuh d'après jeuxvidéo.com, il a eu 10/20''",
"''Tu as tué mon frère ! Tu vas mourir !'' (avec l'accent un peu raciste mais pas trop)",
"''Et ketekeeete bugs graphiques ? MAUDIT SOIS-TUUU LEX LUTHOOOR, TU NE T'ARRÊTERAS DONC JAMAAAIS !!''",
"''En tout cas kekette''",
"''Alors là, allah akbar''",
"''Merci Capitaine Chiant !''",
"''Destiny fun police''",
"''Mickey vous offre votre tête en 3D''",
"''Ça me fait sucer des bites OHOH !' Ça me fait plaisir, c'est super !''",
"''Attendez les gars je craque une boîte''",
"Le bug des munitions lourdes avec le Finis Terrae de ses morts et le Brise-Glace là",
"Le légendaire canyon au-dessus duquel on volait en passereau au début de l'assaut dans la neige, celui qui est horrible en Nuit Noire abyssale là",
"La strat de grosse tante sur les premières Nuits Noires du Nexus, avec 2 mecs cachés derrière un mur et le troisième qui tirait au Brise-Glace d'en haut, mais il devait faire gaffe à pas se faire surprendre par le minotaure qui lui spawnait dans le dos",
"Le farm de kills au super sur les Vex juste avant la dernière salle du Nexus pour avoir les emblèmes de doctrines",
"''Euhhh c'est qui déjà les Vex ?''",
"''Une cascade de lait Vex, oui oui, de lait VEX''",
"''Euhhh, Eris ? Ton caillou, sur ma carte''",
"''Get your rock...OFF MY MAP''",
"''C'est moi qui prends la relique je suis full intel''",
"Le DMR Zèbre sur Halo 4",
"L'AR Requin sur Halo 4",
"La légendaire Charge Adhésive de H4 bordel, quel plaisir",
"La mythique arme de la communauté, et les gros malaises qui s'en servaient pas comme il fallait",
"''Et vous Paul, quand vous est venu le goût de la merde ?''",
"''Pour que j'bande, il faut qu'ma bite soit dans d'la merde''",
"Les carottes sur Battlefield",
"''Gros porc gros SAC de merde''",
"''Abibababapute''",
"''Monsieur Patate, Big Patata !!''",
"''Drrrrraaa Cortex 91 les Pyramides !!''",
"''Diablox9, le gros djique de YouTube''",
"''Wakatépé Baboon''",
"''Akouyamakatché''",
"Le caca du mec espagnol dans le toboggan là",
"Les emblèmes Cimier de Sentinelle et Insigne de Corsaire sur D1 qui sont affreux et pourtant y a toujours un filsdeup qui l'a sur lui à la Tour même 7 ans après putain ça rend ouf",
"Le succès Girouette sur Destiny",
"''Putain les alliééés…''",
"''Lui j'vais lui envoyer un message''",
"''Les poings championgs'' (avec l'accent de Désastre)",
"''Je suis Passe-Partout, de Fort Boyard, je guide les casse-cou, dans les traquenards !!''",
"''Vladimir Pitoune''",
"''J'étais recherché ouais j'étais pas au couraaant, et à la 'zon ils coupaient l'couraaant''",
"''J'ai quitté l'écooole''",
"''À plus tard, batard''",
"''MEGA BOOMAS''",
"''Mi-mi-mi-mi-mi-micro pénis''",
"''Le Roi Heenok est...dans les magazines, sur internet...il pose avec des rougeurs, des... hein ? Toute sorte d'arme à feu !! Sa chaîne touche à son pénis''",
"''TORTAAANK''",
"Le Jury Pendu de la mort qui tue",
"''Le zap de Psion''",
"''Tieeens voilà tes 30 dollars !''",
"''Les Miséroïdes''",
"''Biééé Zixxx''",
"''Non c'est ma faute...ta gueule !''",
"''Le relais-relais...''",
"''Valjean, t'es qu'un pédé !''",
"''Les assauts qui piquent''",
"''RNGésus''",
"''Montréal-Paris t'entends, l'interview que TU veux mettre sur ta cassette, pour qu'tu fais la même chose jeune pédé allez''",
"''Vous faites la paire, le royaume est voué à sa perte !''",
"''Sangocouille''",
"''Monsieur Grenier attention la pelouse est mouillée''",
"Le robot qui détec les mouches qui sont allées sur un cadav, et les vers, les vers de terre qui ont mangé des pecticides",
"''J'vais faire un tooour à la Tooour...''",
"''Et bah moi j'fais rien du touuut''",
"Le Terre Déserte sur D1",
"Le sublime Tlaloc sur D1",
"L'As de Pique, mais de D1",
"''T'inquiète pas ça va bien se passer''",
"''Putaaain taaainpu''",
"''Valus Truc''",
"''Valus Maroilles''",
"''Marwa Looourde''",
"''Imagineeext c'est touuujours plus d'avennntures !''",
"''Gros banger''",
"''Attends je m'assois une minute là''",
"''Mais y a aussi l'garage…mais y a aussi ma bite''",
"''Attention punition divine !''",
"''Le départ est prévu à 1h34 du matin pas 1h34 !!''",
"''Comment vas-tu mon brave Milou, tu n'as pas été trop secoué ? Et vous capitaine, tu n'as pas été trop secoué ?''",
"''No shit Sherlock''",
"''FPC Premier Degré''",
"''MATCH À MORT PAR ÉQUIPE HARDCORE !!''",
"''Holy shit 1v1 situation''",
"''C'est beaucoup trop fort''",
"''Ah bah faudrait savoir...ah bah faudrait s'asseoir !''",
"''Mange ta mère''",
"''Je m'suis fait buter...et on m'a volé mon colis''",
"''Botox dans les fesses !''",
"''Ah j'ai des verrues sous mes fesses ça m'gratte''",
"''Jeunesse Hi-tlerienne !''",
"''Si Jésus Christ n'avait pas existé, en quelle année serait-on aujourd'hui ??''",
"''Pour le courage, pour pas qu'il y ait de failles''",
"Les engrammes bleus qui donnaient des éxotiques sur D1 :)",
"Les engrammes légendaires qui donnaient du bleu sur D1 :(",
"''C'est moi qui les ai plantayyy''",
"''Maat Mons Vénus''",
"''J'ai des connaissances en chimie qu't'as pas : frappe-moi, je t'empoisonne !''",
"''Trop drôle quoi''",
"''Ah ouais c'est marrant...''",
"''Lesssgooo''",
"''Let's go c'est parti''",
"''J'ai envie d'éternoyer''",
"Le titre Chroniqueur pour le grand fou qui a archivé tout ça",
"''Ça marche, charch''",
"''À demain alors''",
"''Oulah, doucement avec la magie''",
"''Le mec pisse quoi''",
"Le script de Franckix pour changer de couleur tout en jouant sur Destiny",
"Revêtement moisi du gland : Calcédoine",
"Les citrouilles qui marchaient pas au début de D1",
"Les tenues Power Rangers de la SRL sur D1",
"Le masque d'Uldren sur Destiny",
"''Il a l'air très remonté par le son du ter-ter...suus''",
"''Les décideurs ! Ça te va les décideurs ?!''",
"''Ça m'énerve, je vais tuer des chiens dans la rue pour me masser les nerfs...eh nan mais attendez j'ai jamais fait ça...c'était pas une rue c'était une avenue''",
"''Le piiire du piiire''",
"''Un jour quand tu seras grannnd...tu deviendras roiii...ou pas''",
"''Bon, comme on est à la fin et qu'tout le monde était trop occupé à s'masturber là, bah on a qu'à dire que Tintin là, pour une raison énigmatique mais valide, et bah il trouve la solution'' (avec l'accent québécois bien cliché)",
"''À en juger par ce visage que toute joie de vivre à quitté, qu'est-ce que Milou vient de renifler…une pâquerette réponse 1, une bougie parfumée réponse 2…les pieds empoisonnés du Capitaine Haddock, réponse 3'' (avec l'accent téxan bien crade)",
"''Allah akbar tabarnak de caribou !!'' (accent québécois évidemment)",
"''Et comment tu comptes t'y prendre hein, tu n'as rien à part tes poignards ridicules et tes prises de karaté minables, contre nos ffflingues !''",
"''Matrixte !''",
"''L'Equalizer''",
"''4 mariages pour 1 lune de mieeel…leeel''",
"''Antonino et Antonino se sont rencontrés sur une gondole à Veniiise…zizi''",
"''Bonjour à toutes les tantouzes, voulez-vous manger les excréments de Dieu ?''",
"''Mes chers cons de métropole, lol''",
"La musique de fin de Equalizer (I'm gonna diiieee alooone…)",
"Le vomi de Rathalos devant le cinéma à la fin de Avatar après avoir passé sa journée à jouer à ce chef d'oeuvre de Pokémon Donjon Mystère Explorateurs du Ciel",
"''J'suis dans le futur t'es le passé composé'' (voix de Booba très mal faite)",
"''Ici le coloneeel, et le Père Noël est très lourd !''",
"La légendaire liste de films à regarder en groupe qu'on a jamais faite",
"Le slip de Kodlak Blancrin dans Skyrim",
"''Ouiii j'entends les chevauuux, oui j'entends les sado-masooooos, trucide-moiii !!''",
"''Ne me manque pas de respect petit...ce serait pas très halal...''",
"''Masturbation totale (masturbation totale), fellation totale (fellation totale), est-ce que tuuu suces'' (avec la mélodie qui va avec)",
"L'ESSAIM sur Destiny",
"Le Journal Tout sur les Jeux",
"The Elder Scrolls Angoulême",
"The Elder Scrolls II : Daggerfall, clairement le meilleur de la série avec Redguard, Shadowkey sur N-Gage et Blades sur téléphone",
"''The Elder Krisprolls''",
"Succès déverrouillé : vous avez trouvé le mémorial pour toutes ces refs du passé comme du futur qui ne seront jamais sur cette liste parce que ça commence à être giga chiant et surtout giga long (comme ma bite lol)",
"''Je la retrouverai grâce à mon Érection du Millénium...ahhh miskine !''",
"''Mon nom est Mamie Tsunako, l'extraordinaire grand-mère''",
"''Quelle coïncidence, il se trouve que je suis moi aussi Mako Tsunami !''",
"Le magnifique Kévin Prototype",
"Les légendaires passereaux Redbull sur Destiny, et comment Franckix les a obtenus",
"La boîte de nuit sur Destiny",
"Summoning Satan",
"La grotte de S8tan et Suspixious",
"Les ours troglodytes de Skyrim",
"Le titre Tire Changer",
"Le titre MMXIXMMXXMMXIXMXMXNXX",
"La chatte à Mireille",
"''Ohhh chatte à poils !''",
"Le pote de Mjoll la Lionne dans Skyrim",
"''Voilà''",
"''Alors ça tu vois c'est un kiki !''",
"''C'est pas l'tout mais l'tampax !''",
"''Nicole...ouvre...ouvre-moi''",
"''Mais moi j'veux faire l'amooour !! J'veux faire l'amouhouhour ! (T'es un malade Bernard ! Un malade !!)''",
"La technique de la Tour Eiffel",
"Cette grosse pute de barre transversale sur Rocket League",
"''Il fait trop chaud dans mon pays''",
"''Je suis une saucisse islamiste (AU S'COOOURS !!)''",
"''Je suis une merdeuh''",
"''Sébastien Chabal ! OUI !!''",
"Le Docteur Méchant sur Destiny",
"''Ah batard tu fumes''",
"''On aurait dû faire c'qu'on aurait dû faire''",
"Supercopter l'hélicoptère",
"Le super pénis",
"''Je parie mon pénis qu'ils se sont déjà enfuis...''",
"''Wagner qui jouait avec des p'tites voitures''",
"''Oh et cette tête, oh quelle horrible tête !''",
"''Ameno…Ameno dooore…Ameno dori meee'' (avec la mélodie sinon Dieu te punit poil au kiki)",
"''Pour votre santé mangez 5 fruits et légumes par jour sinon vous mourez direct !''",
"''Captaaain Diabèèète ! Captaaain Diabète ! Quand ton taux de glicémie a dépassé 3, les enfants du monde entier se tournent vers toi'' (ton ni nununununuuu ninuuu)",
"J'ai demandé de la thuuuune, à mes parents si s'en avaient. Jvouslais m'acheter un Kebaaaabe et puis un téléphone 5G. Et ils mon dit : 'Impeccableeee, ta plus qu'a te mettre à bosser'. Mais comme j'en branle pas uuuuune, Je suis aller sous l'canapé (Air D'indochine)"]
